### ISSUE TITLE
fix: Android Studio IDE run button not working  ( getting gradle exception)

### ISSUE THREAD

**Issue by RR-Reddy** [VeryGoodOpenSource/very_good_cli#101]
**Description**
The following is the error log, When i run on Android studio IDE run button.
![Screenshot from 2021-03-02 21-05-48](https://user-images.githubusercontent.com/32235964/109672950-8b2c0f80-7b9b-11eb-883b-281c98b42b78.png)

**Steps To Reproduce**

1. run command: very_good create my_app
2. open project in android studio
3. select staging ( run configuration) 
3. click on install button ( Green color run button) 
4. Seeing error as above screenshot

**Expected Behavior**
after tap on android studio run button, android app should be build and install into any available or target device/simulator.

**My workaround notes**
1.app is build success and installed into target device when i used command in teriminal
  command : **flutter run --flavor staging --target lib/main_staging.dart**

2. i have made below change ( added flavor argument in IDE run configuration as below ) and working as expected
    only diff is line number 3 added.
![Screenshot from 2021-03-02 21-18-22](https://user-images.githubusercontent.com/32235964/109674345-ddb9fb80-7b9c-11eb-813e-e5e6848f9749.png)

**Comment by felangel** [comment]
@RR-Reddy this has been fixed as part of v0.1.3 🎉
