### ISSUE TITLE
New Very Good CLI Release - 0.20.1

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_cli#1028]
**Description**
Need to create a new release for Very Good CLI to get some bug fixes released.

**Requirements**
- New release is created and tagged in the repo
- New release is pushed out via Pub.dev
- Confirm that our release documentation is actually up to date and useable. If not make the needed changes.

**Comment by alestiago** [comment]
This seems to have been closed by https://github.com/VeryGoodOpenSource/very_good_cli/issues/1035.
