### ISSUE TITLE
fix: Unable to Change Kotlin Version

### ISSUE THREAD

**Issue by gabrielmcreynolds** [VeryGoodOpenSource/very_good_cli#1055]
**Description**
I have created a Flutter app using Very Good Cli. Now, when I try and run it on Android I get the following error:
```

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Users/gabrielmcreynolds/StudioProjects/sightseer/android/build.gradle:             │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
``` 

Looking online, see the [solution](https://docs.flutter.dev/release/breaking-changes/kotlin-version) is to change the ext.kotlin_version to the latest version (which is currently 2.0.0).

However, looking at the build.gradle generated by Very Good Cli there is no field for `ext.kotlin_version`

My build.gradle
```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```
I even tried to add the following to the top of my `build.gradle` but still get the same error.

```
buildscript {
    ext {
        kotlin_version = '2.0.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Steps To Reproduce**

1. Generate Flutter Project using Very Good Cli
2. Run Development Flavor
3. View error listed above

**Expected Behavior**
The `build.gradle` would have a `ext.kotlin_version` property.

**Comment by tomarra** [comment]
Hi @gabrielmcreynolds 👋 Thanks for opening this issue!

This is actually working as designed as that block was removed from the template[ in a previous PR](https://github.com/VeryGoodOpenSource/very_good_templates/pull/70/files#diff-b14e321f4bef3fee1a71bb01d865abec67b56da67aa12a3a73379ab8647451b7). In fact if you do a `flutter create` without the Very Good CLI the `build.gradle` file that it produces no longer has that section either.

If your looking to add it back in you can take a look at the PR that removed it for the correct syntax but overall that seems like maybe something is out of sync with the Flutter documentation as well.

Closing this as "won't fix"
