### ISSUE TITLE
App has errors in app_localizations.dart after `very_good create`

### ISSUE THREAD

**Issue by icodeyou** [VeryGoodOpenSource/very_good_cli#1065]
**Description**

**Steps To Reproduce**

1. Run this command in your terminal : `very_good create flutter_app foo`
2. Go to the folder `foo/`
4. Run the command : `flutter run --flavor development -t lib/main_development.dart`

5. I see the error :
```
Error (Xcode): lib/l10n/l10n.dart:2:8: Error: Error when reading '../../../../../../../.pub-cache/hosted/pub.dev/flutter_gen-5.5.0+1/lib/gen_l10n/app_localizations.dart': No such file or directory
```

**Expected Behavior**
The code should compile after `very_good create flutter_app foo`

**Screenshots**
<img width="434" alt="image" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/15326889/69ff0e8a-714c-423a-9e50-4f08c9ec6e91">

**Additional Context**
FYI, the error only occurs for common names. If I use a unique ID as the name of the app, it will work (ex : `very_good create flutter_app xyz_abk_ojp`)

I am on macOS M2, Sonoma 14.5
very_good version : 0.22.0
Flutter version : 3.22.2

**Comment by alestiago** [comment]
Thanks @icodeyou for opening this issue. Can you include a sample of how does your `pubspec.yaml` look like? Does it have `flutter_gen: any`, if so, if you remove it and try again does it work?

**Comment by tomarra** [comment]
Hi @icodeyou 👋 Given there isn't any new information on this and there is a proposed fix environment wise from @SamC-Apadmi I'm going to close this out as there isn't a code change that were going to make for this. If your still having issues feel free to reopen this ticket with more details.

**Comment by ng-cen** [comment]
this works for me: https://github.com/flutter/flutter/issues/147047#issuecomment-2067599679

After commenting it out the below line in pubspec.yaml it worked.
```yaml
flutter_localizations:
sdk: flutter
intl: any
#flutter_gen: any
```
