### ISSUE TITLE
chore: Confirm Flutter 3.24.0 and Dart 3.5 Support

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_cli#1110]
**Description**

With the release of Flutter 3.24.0 and Dart 3.5 some things are breaking. Need to review the package and make any necessary fixes.

**Requirements**

- [ ] Package works correctly on Flutter 3.24.0 and Dart 3.5

**Comment by alestiago** [comment]
If we want to bump `mason_logger` to latest, we are blocked by https://github.com/felangel/mason/pull/1398

**Comment by tomarra** [comment]
Closed out and released via #1125
