### ISSUE TITLE
docs: available commands are unclear 

### ISSUE THREAD

**Issue by Add00w** [VeryGoodOpenSource/very_good_cli#113]
**I come across this cli and tried to read it but didn't get too much info, then I ignored it and few days later I got [this](https://pub.dev/packages/get_cli) from get, all the commands where listed in read me and clear then thought to ask you if you can list most of the commands like get or it is different.**
thanks.

sorry I just got bug template.

**Comment by felangel** [comment]
Hi @EngAddow 👋 
Thanks for opening an issue!

We tried to document the available commands in the [README Commands Section](https://github.com/VeryGoodOpenSource/very_good_cli#commands). In addition, the [complete usage](https://github.com/VeryGoodOpenSource/very_good_cli#-very_good---help) is included.

Currently, there is just a single "useful" command (`create`) 😄 

Can you please describe what you'd rather see? Thanks! 🙏

**Comment by Add00w** [comment]
Sorry, I am bloc user and try to follow what is new and saw the cli from getX and thought this is the same, I misunderstood the purpose of this cli sorry again.
