### ISSUE TITLE
fix: very_good update fails on dart 3.5.3

### ISSUE THREAD

**Issue by Laebrye** [VeryGoodOpenSource/very_good_cli#1156]
### Description

Haven't used the CLI for a while so decided to do so when starting a new project. Got the prompt to update but when running the `very_good update` command I got the following errors:

```
../../.pub-cache/hosted/pub.dev/win32-5.1.1/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/win32-5.1.1/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/win32-5.1.1/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/win32-5.1.1/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/win32-5.1.1/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
```

From a very brief scan of the internet it looks like there might be a deprecated class being used by a package dependency in the update code.

### Steps To Reproduce

1. have dart 3.5.3 installed 
2. run `very_good update`

### Expected Behavior

very_good cli updates without any issues.

### Additional Context

Am using the version of dart bundled with the latest stable version of flutter

**Comment by tomarra** [comment]
Hi @Laebrye 👋 

Unfortunately there was a breaking change in Dart 3.5 and the workaround is not fun. What we have suggested to most people is to [uninstall](https://dart.dev/tools/pub/cmd/pub-global#deactivating-a-package) and then [reinstall](https://cli.vgv.dev/docs/overview#installing) the CLI to ensure everything gets lined up correctly. Give that a shot and let us know if your still running into problems.

**Comment by Laebrye** [comment]
Ahhh - turning it off and on again. Why didn't I think of that? 😄 

Worked like a charm. Thank you - I will close the issue
