### ISSUE TITLE
fix: omit type annotations for local variables warning

### ISSUE THREAD

**Issue by zyllus17** [VeryGoodOpenSource/very_good_cli#116]
**Description**
I am getting `omit type annotations for local variables` whenever annotating the local varible

**Steps To Reproduce**

Creating a local variable in a function

**Expected Behavior**
Avoiding the error

**Screenshots**
![image](https://user-images.githubusercontent.com/50977126/113457131-a30de200-942c-11eb-9645-68ff49c84033.png)

**Additional Context**
On further inspection I found that I can supress the warning by commenting it or by turning it off in the analyzer.
I prefer annotating variables as it becomes more clearer and easier for me to understand at a later point of time. 
It is turned on by the CLI, 
**I would like to know if annotating is good or bad and why I shouldn't use it**

**Comment by mrverdant13** [comment]
As you found out, this is related to the project linter rules.

In this case, we are talking about the [omit_local_variable_types](https://dart-lang.github.io/linter/lints/omit_local_variable_types.html).

![Omit local variable typing screenshot example](https://user-images.githubusercontent.com/42245236/113467302-c2dedf00-9407-11eb-8f67-a7c63076b963.png)

The rule states that type inference is enough.

> **CONSIDER** omitting type annotations for local variables.
> 
> Usually, the types of local variables can be easily inferred, so it isn't necessary to annotate them.

The keyword here is **CONSIDER**. You might do it or not. There won't be any critical impact on your app.
