### ISSUE TITLE
build: Update bundle with newest gradle plugin version

### ISSUE THREAD

**Issue by mrverdant13** [VeryGoodOpenSource/very_good_cli#118]
**Description**
The gradle version might be pumped to meet the current base Flutter project setup.

**Steps To Reproduce**

1. Go to `your_project\android\build.gradle`
2. See `buildscript.dependencies` and you will find that the current plugin version is `3.6.3`.

**Expected Behavior**
At the moment, the `flutter create` command already sets the plugin version to `4.1.0`.
No huge impact on builds but just for the sake of consistency.

**Screenshots**
![image](https://user-images.githubusercontent.com/42245236/113996453-ce257680-981c-11eb-8742-f3fda41e615e.png)

**Additional Context**
very_good version: 0.1.7

Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (3 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

**Comment by felangel** [comment]
Hi @mrverdant13 👋 
Thanks for opening an issue!

The gradle version was downgraded due to https://github.com/VeryGoodOpenSource/very_good_cli/issues/104. Can you confirm that you're not experiencing any build issues on Android? I'll double check as well as soon as I can, thanks! 🙏

**Comment by mrverdant13** [comment]
Hello, @felangel 

I just tested the base project on some Android devices with no bugs at all.

Besides that, the only possible issue I found is related to the Android `queries` element as described [here](https://developer.android.com/studio/releases/gradle-plugin#4-0-0).

In short, there is a minimum plugin version regarding compatibility:

![image](https://user-images.githubusercontent.com/42245236/114257557-67bc6780-9986-11eb-8dc6-f6b5e65e5255.png)

The current plugin version is `3.6.3`. This might be upgraded to `3.6.4` to meet this requirement.
However, since I could test the base app with `4.0.1` version without issues, I think it is pretty safe bet.

**Comment by felangel** [comment]
Working on this however I think we need to wait until the fix has made it's way into stable (https://github.com/flutter/flutter/issues/82262)

**Comment by MaximilianFrick** [comment]
Still facing problems when using flavors and current flutter version in combination with gradle version 4.1.0 or above

I am using
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale de-DE)
    • Flutter version 2.2.3 at /Users/whoogle/Documents/development/flutter
    • Framework revision f4abaa0735 (vor 6 Tagen), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

and with gradle version 4.1.0 I still get the same error as described in the beginning. 

Only solution what helped was downgrading version to 3.5.4
