### ISSUE TITLE
feat: Add support for fvm

### ISSUE THREAD

**Issue by b099l3** [VeryGoodOpenSource/very_good_cli#124]
**Is your feature request related to a problem? Please describe.**
When I have been creating projects I have been using [fvm](https://github.com/leoafarias/fvm) to keep the flutter version set on a project level rather than on an environment level

**Describe the solution you'd like**
I was thinking of adding a flag to support the version of flutter you require on the project. This would then create the required .fvm folder with the required version. e.g.,
`very_good create my_app --fvm stable`
`very_good create my_app --fvm 2.0.1`

it could also check if fvm is installed or check that the version specified is installed and install it.

**Describe alternatives you've considered**
The alternative is to manually do this step

**Additional context**
This may have been something already considered and not appropriate for this tool. i.e., not wanting to take a dependency on fvm. Or not within the scope of this CLI tool - setting up the environment.

This will have a knock-on effect on the other package dependencies, so maybe too much as we will always have the latest Flutter version. In which case it could just set up the fvm folder for the support version of flutter of the bloc version. Sorry that may have sounded more complicated

**Comment by felangel** [comment]
Hi @b099l3 👋 
Thanks for opening an issue!

As stated in our [contributing guidelines](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/CONTRIBUTING.md) we are currently not accepting feature requests.

> At this time, we welcome bug tickets but will not be accepting feature requests because the roadmap and scope of this project is still being defined. In addition, we understand that Very Good Core is basic and lacks many features that might be desirable in a starter application but this is a conscious decision made to keep the scope of Very Good Core focused to just foundational items. In the future, we may support additional, more feature-rich templates but at this time we would ask that issues be reserved for bugs only.

Sorry for any inconvenience!

**Comment by b099l3** [comment]
No problem, sorry this is my fault for not reading the contributing guidelines.

**Comment by felangel** [comment]
> No problem, sorry this is my fault for not reading the contributing guidelines.

No worries! Thanks for opening an issue and we will keep this in mind for once the roadmap for very good cli has been finalized 👍
