### ISSUE TITLE
Localization not generated

### ISSUE THREAD

**Issue by mstfkhazaal** [VeryGoodOpenSource/very_good_cli#125]
When I add words to translation, Flutter does not create them directly.
How do I make it automatic?

**Comment by felangel** [comment]
Hi @mstfkhazaal 👋
Thanks for opening an issue!

The strings should be available in flutter the next time you call `flutter run` or `flutter packages get`.

Let me know if that helps 👍

**Comment by mstfkhazaal** [comment]
`flutter packages get ` and `flutter run`  is not work
I use **vs code** and **android studio**

**Comment by mstfkhazaal** [comment]
`flutter packages get ` and `flutter run`  is not work
I use **vs code** and **android studio**

**Comment by felangel** [comment]
> `flutter packages get ` and `flutter run` is not work
> I use **vs code** and **android studio**

Can you please share the error you’re seeing? Thanks!

**Comment by mstfkhazaal** [comment]
**Arb File**  I add test_translate
![Arb](https://user-images.githubusercontent.com/47450090/118371437-5b46b280-b5b5-11eb-85f7-36f881433b24.png)
I run` flutter packages get ` 
![get Package](https://user-images.githubusercontent.com/47450090/118371436-5aae1c00-b5b5-11eb-9b11-4e770a3f4899.png)
and I run **debugging web** developement and I can't get `test_translate`
![Error](https://user-images.githubusercontent.com/47450090/118371435-5a158580-b5b5-11eb-96c3-2d25452b6f4e.png)

**Comment by mstfkhazaal** [comment]
Run on Android takes a lot of time. One cannot wait for each modification to Arb files

**Comment by felangel** [comment]
If you’re having trouble with performance or the analysis server then I suggest opening an issue in the Flutter repo as very_good_cli is just using the officially recommended tooling for localization. In this case, it might just be a dart analysis issue where it doesn’t detect changes to the generated file unless you explicitly navigate to the file or force a restart of the analysis server.

**Comment by mstfkhazaal** [comment]
Well, thank you
There is a plugin called **flutter intl** that most people use and I've used in my projects.
Is there a way to combine it with **very-good-cli** in the future

**Thank you and your team for these libraries**

**Comment by felangel** [comment]
> Well, thank you
> There is a plugin called **flutter intl** that most people use and I've used in my projects.
> Is there a way to combine it with **very-good-cli** in the future
> 
> **Thank you and your team for these libraries**

Feel free to adjust your project and include any dependencies you see fit. For now, the goal of very_good_cli is to provide the core starter code needed for most projects. In the future may support multiple templates 👍
