### ISSUE TITLE
fix: AppLocalizations errors on pubspec update

### ISSUE THREAD

**Issue by adamsmaka** [VeryGoodOpenSource/very_good_cli#139]
**Description**
Every time I update a pubspec.yaml file, everything connected with AppLocalizations throws errors and the only solution to fix it is to restart IDE.

**Steps To Reproduce**
1. Go to 'pubspec.yaml'
2. Add dependency
3. Save the file
4. See error everywhere

**Screenshots**
![Screenshot from 2021-06-03 10-15-32](https://user-images.githubusercontent.com/22574704/120611913-eef0fd80-c454-11eb-8e96-90088f53fc3e.png)

**Additional Context**
Ubuntu 20.4 / Flutter 2.2.1

**Comment by felangel** [comment]
Hi @adamsmaka 👋
Thanks for opening an issue!

It looks like you haven’t run `flutter packages get` in order to generate the dart localization files. Let me know if that helps 👍

**Comment by adamsmaka** [comment]
it helps! thank you!

**Comment by gyakhoe** [comment]
> Yeah, as @gyakhoe noticed it's still appearing from time to time. Can we do anything about it or is it something with AppLicalizations? Only closing and reopening the ide solves the problem.

I don't know if you know already or not. You can open .dart_tool/package_config.json file and hit save once. It removes the error if any after pubspec update.
