### ISSUE TITLE
feat: Support plain dart package generation

### ISSUE THREAD

**Issue by definitelyokay** [VeryGoodOpenSource/very_good_cli#146]
**Description**
I was thinking it would be nice to be able to generate an opinionated Dart package starter project that's already hooked up to use [very_good_analysis](https://pub.dev/packages/very_good_analysis), [mocktail](https://pub.dev/packages/mocktail), [test_coverage](https://pub.dev/packages/test_coverage) and/or anything else that would be helpful to use by default.

For reference, this is the usual Dart command which generates a new Dart package:

`dart create --template package-simple my_package`

I realized I would be repeating the same steps as the package creation steps [here](https://github.com/definitelyokay/app_http_client#create-a-dart-package) for every Dart package I wanted to make, hence this suggestion.

**Comment by rishabhdeepsingh** [comment]
why not use alias?

**Comment by felangel** [comment]
This is now available in [v0.3.0](https://pub.dev/packages/very_good_cli/versions/0.3.0) 🎉 

Check out the [release notes](https://github.com/VeryGoodOpenSource/very_good_cli/releases/tag/v0.3.0) for usage information.
