### ISSUE TITLE
Generated Project Open in Intellij 

### ISSUE THREAD

**Issue by cyrsis** [VeryGoodOpenSource/very_good_cli#157]
**Description**
Loved the tools, Generated Project need some manual adjustment before it can run the project

**Steps To Reproduce**
```
very_good create budgetpos --org-name works.budgetapp.budgetpos
```
![image](https://user-images.githubusercontent.com/731087/126887340-f231bd98-f65f-49aa-a5b8-83868cc4d27a.png)

**Comment by denangelov** [comment]
Hi @cyrsis! 

We investigated the issue you reported and were unable to reproduce the error. Based on your screenshot, it seems like you may be missing some of the project files (see screenshot). Are you able to share your output of running `very_good create budgetpos --org-name works.budgetapp.budgetpos`?

![Screen Shot 2021-07-27 at 1 40 55 PM](https://user-images.githubusercontent.com/20870559/127209769-f094859a-2abe-45e9-8303-7a6c2c0bc586.png)

**Comment by cyrsis** [comment]
Sorry for the delay, looks like working fine for now.

Updated the CLI and looks like it is working well and love the new feature for the package
