### ISSUE TITLE
feat: expose command to install dependencies with recursive support

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_cli#174]
**Description**
As a developer, I want to be able to install dependencies for all packages within my current project. The command should ideally automatically determine whether to run `flutter packages get` or `flutter pub get` depending on the type of package and should be capable of recursively running the install command for each nested package.

**Proposed Usage**
```sh
# Install dependencies for the current package via `flutter packages get` or `flutter pub get`
very_good packages get

# Install dependencies recursively via `flutter packages get` or `flutter pub get`
very_good packages get --recursive
very_good packages get -r
```

**Additional Context**
very_good_cli already contains the functionality as part of https://github.com/VeryGoodOpenSource/very_good_cli/blob/ee37acd2f0ff1651a36f224c926110f3f55fd9b6/lib/src/flutter_cli.dart#L11 and addressing this issue would require exposing that functionality via a new command.

Related Issue on Flutter: https://github.com/flutter/flutter/issues/89180

**Comment by orestesgaolin** [comment]
It would be awesome to specify `flutter` version to be used e.g. by path or `fvm`

**Comment by felangel** [comment]
> It would be awesome to specify `flutter` version to be used e.g. by path or `fvm`

I would expect the command to run using whatever configured flutter version you already have. Can you provide a bit more context regarding the use-case and what the usage would look like? Thanks!

**Comment by orestesgaolin** [comment]
Using `fvm` I specify the flutter version to be used per directory basis. It may mean that I don't have `flutter` available globally or it can link to the different version of `flutter` than globally accessible. This would be the version that I'd like to use when resolving dependencies for a given project.

Some tools (like `pubviz` or bash scripts using `flutter` internally) require additional steps to make this happen like overriding `flutter` for the scope of a program, or temporarily changing `flutter` to link to the desired version, or sometimes even modifying the script itself. Being able to pass: `very_good packages get --fluter ~/fvm/versions/beta/bin/` could be really handy.
