### ISSUE TITLE
fix: Package directive doesn't match file location

### ISSUE THREAD

**Issue by sebastianhaberey** [VeryGoodOpenSource/very_good_cli#175]
**Description**
Android Studio gives a warning about omitted root packages in Kotlin. I guess this is not really a bug (feel free to close it), more a question on my part: was this a conscious design decision to leave out the root packages (com.example.foo) in the directory structure?

**Steps To Reproduce**

1. `very_good create --org-name com.example --template flutter_plugin foo`
2. Open directory foo/foo_android/android in Android studio
3. Open source file src/main/kotlin/foo/FooPlugin.kt
4. Inspection for package declaration `package com.example.foo` says "Package directive doesn't match file location"

**Comment by marcossevilla** [comment]
Hi @sebastianhaberey, there's a problem with organization name parsing apparently. We're working on the fix now, thanks for noticing!
