### ISSUE TITLE
fix: java.lang.ClassNotFoundException: Didn't find class "com.example.verygoodcore.MainActivity"

### ISSUE THREAD

**Issue by ketulrastogi** [VeryGoodOpenSource/very_good_cli#196]
**Description**
A newly created app doesn't run for Development, Staging, or Production environment. It always returns ClassNotFoundException

**Steps To Reproduce**

1. Generate a new app using Very_Good_Cli version 0.4.4 and run it in any environment.

**Outputs**

1. Flutter Doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code
[✓] VS Code, 64-bit edition (version 1.60.2)
[✓] Connected device (3 available)

• No issues found!`

2. Very Good Cli Version: 0.4.4

3. Flutter Run
[ +156 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1149 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[   +1 ms] executing: [C:\flutter/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[ +221 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] 2.5.1
[  +19 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +75 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +227 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +128 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +142 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +100 ms] List of devices attached
           HS1202017111448        device product:HS117 model:Capture_ device:rimoB transport_id:3
[  +14 ms] C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell getprop
[ +108 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +191 ms] Initializing file store
[  +22 ms] Done initializing file store
[  +56 ms] Skipping target: gen_localizations
[   +3 ms] Persisting file store
[   +9 ms] Done persisting file store
[  +18 ms] Skipping pub get: version match.
[ +418 ms] Generating D:\KetulRastogi\Samples\sampleapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +128 ms] ro.hardware = qcom
[ +114 ms] Initializing file store
[        ] Done initializing file store
[  +12 ms] gen_localizations: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\flutter\packages\flutter_tools\lib\src\build_system\targets\localizations.dart,D:\KetulRastogi\Samples\sampleapp\l10n.yaml,D:\KetulRastogi\Samples\sampleapp\lib/l10n/arb\app_en.arb,D:\KetulRastogi\Samples\sampleapp\lib/l10n/arb\app_es.arb,D:\KetulRastogi\Samples\sampleapp\.dart_tool\flutter_gen\gen_l10n\app_localizations_en.dart,D:\KetulRastogi\Samples\sampleapp\.dart_tool\flutter_gen\gen_l10n\app_localizations_es.dart,D:\KetulRastogi\Samples\sampleapp\.dart_tool\flutter_gen\gen_l10n\app_localizations.dart}
[ +234 ms] Skipping target: gen_dart_plugin_registrant
[   +2 ms] gen_localizations: Complete
[   +5 ms] Skipping target: _composite
[   +4 ms] complete
[  +10 ms] Launching lib/main_production.dart on Capture in debug mode...
[  +12 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\KETULR~1\AppData\Local\Temp\flutter_tools.94ba1848\flutter_tool.b36a6705\app.dill --packages D:\KetulRastogi\Samples\sampleapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\4f2a58af27abc49ecf55570043bbf938.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +17 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +171 ms] Exit code 0 from: C:\Users\KetulRastogi\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.verygoodcore.dev" (Raw: "com.example.verygoodcore.dev")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="Sampleapp" (Raw: "Sampleapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.verygoodcore.MainActivity" (Raw: "com.example.verygoodcore.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040003
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +13 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell -x logcat -v time -t 1
[  +24 ms] <- compile package:sampleapp/main_production.dart
[ +238 ms] --------- beginning of main
           09-30 11:55:47.370 D/KeyguardUpdateMonitor( 2030): handleBatteryUpdate
[  +22 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +51 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +108 ms] Building APK
[  +41 ms] Using gradle from D:\KetulRastogi\Samples\sampleapp\android\gradlew.bat.
[  +12 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+2381 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [D:\KetulRastogi\Samples\sampleapp\android/] D:\KetulRastogi\Samples\sampleapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=D:\KetulRastogi\Samples\sampleapp\lib/main_production.dart -Pdart-defines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleProductionDebug
[+3759 ms] > Configure project :app
[        ] WARNING: DSL element 'useProguard' is obsolete.
[        ] It will be removed in version 5.0 of the Android Gradle plugin.
[        ] Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard.
[+4781 ms] > Task :app:compileFlutterBuildProductionDebug
[        ] [ +195 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1298 ms] [+1294 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] [   +1 ms] executing: [C:\flutter/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[  +93 ms] [ +107 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] [        ] 2.5.1
[        ] [  +17 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +110 ms] [  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +95 ms] [  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[ +203 ms] [ +134 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +94 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[ +191 ms] [ +116 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +202 ms] [ +249 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +91 ms] [ +107 ms] Initializing file store
[  +95 ms] [  +50 ms] gen_localizations: Starting due to {}
[ +300 ms] [ +297 ms] Skipping target: gen_dart_plugin_registrant
[        ] [   +5 ms] gen_localizations: Complete
[        ] [  +15 ms] kernel_snapshot: Starting due to {}
[        ] [  +29 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages D:\KetulRastogi\Samples\sampleapp\.dart_tool\package_config.json --output-dill D:\KetulRastogi\Samples\sampleapp\.dart_tool\flutter_build\c7f665df265046e023a120a3c3419db5\app.dill --depfile D:\KetulRastogi\Samples\sampleapp\.dart_tool\flutter_build\c7f665df265046e023a120a3c3419db5\kernel_snapshot.d package:sampleapp/main_production.dart
[+25300 ms] [+25298 ms] kernel_snapshot: Complete
[+1795 ms] [+1738 ms] debug_android_application: Starting due to {}
[ +507 ms] [ +518 ms] debug_android_application: Complete
[+1497 ms] [+1544 ms] Persisting file store
[  +95 ms] [  +19 ms] Done persisting file store
[        ] [  +24 ms] build succeeded.
[        ] [  +31 ms] "flutter assemble" took 29,966ms.
[ +311 ms] [ +260 ms] ensureAnalyticsSent: 254ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +790 ms] > Task :app:packLibsflutterBuildProductionDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preProductionDebugBuild UP-TO-DATE
[        ] > Task :app:compileProductionDebugAidl NO-SOURCE
[        ] > Task :app:compileProductionDebugRenderscript NO-SOURCE
[ +108 ms] > Task :app:generateProductionDebugBuildConfig
[  +95 ms] > Task :app:checkProductionDebugAarMetadata
[        ] > Task :app:cleanMergeProductionDebugAssets UP-TO-DATE
[        ] > Task :app:mergeProductionDebugShaders
[        ] > Task :app:compileProductionDebugShaders NO-SOURCE
[        ] > Task :app:generateProductionDebugAssets UP-TO-DATE
[        ] > Task :app:mergeProductionDebugAssets
[ +689 ms] > Task :app:copyFlutterAssetsProductionDebug
[        ] > Task :app:generateProductionDebugResValues
[        ] > Task :app:generateProductionDebugResources
[+3705 ms] > Task :app:createProductionDebugCompatibleScreenManifests
[        ] > Task :app:extractDeepLinksProductionDebug
[ +107 ms] > Task :app:processProductionDebugMainManifest
[        ] > Task :app:processProductionDebugManifest
[        ] > Task :app:mergeProductionDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:javaPreCompileProductionDebug
[ +284 ms] > Task :app:checkProductionDebugDuplicateClasses
[        ] > Task :app:processProductionDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeProductionDebugJniLibFolders
[ +109 ms] > Task :app:mergeProductionDebugResources
[        ] > Task :app:validateSigningProductionDebug
[        ] > Task :app:processProductionDebugManifestForPackage
[        ] > Task :app:desugarProductionDebugFileDependencies
[+1292 ms] > Task :app:compressProductionDebugAssets
[ +510 ms] > Task :app:processProductionDebugResources
[        ] > Task :app:compileProductionDebugKotlin
[ +189 ms] > Task :app:compileProductionDebugJavaWithJavac
[        ] > Task :app:compileProductionDebugSources
[ +302 ms] > Task :app:dexBuilderProductionDebug
[ +899 ms] > Task :app:mergeExtDexProductionDebug
[ +493 ms] > Task :app:mergeProductionDebugJavaResource
[ +300 ms] > Task :app:mergeDexProductionDebug
[+2202 ms] > Task :app:mergeProductionDebugNativeLibs
[ +600 ms] > Task :app:stripProductionDebugDebugSymbols
[        ] Unable to strip the following libraries, packaging them as they are: libflutter.so.
[+3906 ms] > Task :app:packageProductionDebug
[ +393 ms] > Task :app:assembleProductionDebug
[  +96 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 57s
[   +1 ms] 32 actionable tasks: 31 executed, 1 up-to-date
[+1199 ms] calculateSha: LocalDirectory: 'D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk'/app.apk
[+1669 ms] ✓  Built build\app\outputs\flutter-apk\app-production-debug.apk.
[  +21 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[ +246 ms] Exit code 0 from: C:\Users\KetulRastogi\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.verygoodcore" (Raw: "com.example.verygoodcore")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="Sampleapp" (Raw: "Sampleapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.verygoodcore.MainActivity" (Raw: "com.example.verygoodcore.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040003
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on Capture.
[        ] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell am force-stop com.example.verygoodcore
[ +127 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell pm list packages com.example.verygoodcore
[ +954 ms] package:com.example.verygoodcore
           package:com.example.verygoodcore.dev
[   +2 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell cat /data/local/tmp/sky.com.example.verygoodcore.sha1
[  +80 ms] 75d512dfc08711a79c2eb218acf30f14f14dd96d
[   +1 ms] Installing APK.
[   +2 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 install -t -r D:\KetulRastogi\Samples\sampleapp\build\app\outputs\flutter-apk\app.apk
[+12953 ms] Performing Streamed Install
            Success
[   +3 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell echo -n 4eca204772fe8a0c32a45ed47b097aaa5932e773 > /data/local/tmp/sky.com.example.verygoodcore.sha1
[  +73 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell -x logcat -v time -t 1
[ +337 ms] --------- beginning of main
           09-30 11:57:05.660 I/zygote64(27269): The ClassLoaderContext is a special shared library.
[  +18 ms] executing: C:\Users\KetulRastogi\AppData\Local\Android\sdk\platform-tools\adb.exe -s HS1202017111448 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.verygoodcore/com.example.verygoodcore.MainActivity
[ +217 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.verygoodcore/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +236 ms] E/AndroidRuntime(27337): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(27337): Process: com.example.verygoodcore, PID: 27337
[        ] E/AndroidRuntime(27337): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.verygoodcore/com.example.verygoodcore.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.verygoodcore.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/lib/arm64, /data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
[        ] E/AndroidRuntime(27337): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(27337): 	at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread.main(ActivityThread.java:6501)
[        ] E/AndroidRuntime(27337): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(27337): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime(27337): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[        ] E/AndroidRuntime(27337): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.verygoodcore.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/lib/arm64, /data/app/com.example.verygoodcore-zlP3FKLF-ydFu_R3b3uM3w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
[        ] E/AndroidRuntime(27337): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
[        ] E/AndroidRuntime(27337): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[        ] E/AndroidRuntime(27337): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[        ] E/AndroidRuntime(27337): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1175)
[        ] E/AndroidRuntime(27337): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
[        ] E/AndroidRuntime(27337): 	... 9 more
Exited (1)

I am not able to run the app. Please help me to fix this.

Thanks
Ketul

**Comment by ketulrastogi** [comment]
The same happens for Flutter (Channel stable, 2.5.1).

**Comment by marcossevilla** [comment]
hi @ketulrastogi! The problem is that the CLI isn't generating the MainActivity.kt file, you can add it to `android/app/src/main/kotlin/com/example/veryGoodCore/MainActivity.kt` with the following content:

```dart
package com.example.veryGoodCore

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {

}
```

We're working on a fix so I'll keep you posted on this issue. Thanks for the heads up!

**Comment by ketulrastogi** [comment]
This fixes it for now.
Please add functionality to create MainActivity.kt using the CLI

Thanks

**Comment by marcossevilla** [comment]
hi @ketulrastogi, you can update to [v0.4.5](https://github.com/VeryGoodOpenSource/very_good_cli/releases/tag/v0.4.5) to have the fixes for your issue. Thanks again for reporting! 💯

**Comment by ketulrastogi** [comment]
@felangel @marcossevilla Thanks for the superfast fix for the issue.
