### ISSUE TITLE
Feature Request: With more production examples like signin

### ISSUE THREAD

**Issue by theowenyoung** [VeryGoodOpenSource/very_good_cli#221]
Hi, Thanks for your great job! I'm new to flutter, and I like your design.

But the demo is so simple, It's just a counter, would you like add some more complex example page, like signin, database, or router?

Thanks!

**Comment by jorgecoca** [comment]
Hi @theowenyoung 👋 !

Thank you so much for the feedback! As of now, we do not have plans in the short term to increase the feature set of `very_good_cli`, but there are a few public resources that can help you to expand your Flutter knowledge, as well as `flutter_bloc` and testing:

* https://github.com/flutter/photobooth
* https://github.com/felangel/bloc/tree/master/examples

Hope this helps! Thank you!

**Comment by theowenyoung** [comment]
Thanks, @jorgecoca , this can help a lot!
