### ISSUE TITLE
Bug: Missing Simulators in Xcode

### ISSUE THREAD

**Issue by Hauglid** [VeryGoodOpenSource/very_good_cli#231]
**Description**
No Simulators are showing in Xcode 13.1. 
They do show in a new "flutter create" project, but not with "very_good create"

**Steps To Reproduce**
1. Open terminal, 
2. enter `very_good create appname`
3. Run any of the configurations in vscode.
4. Open .xcworkspace in xcode.
5. No simulators are showing. 

**Expected Behavior**
A list of available Simulators. 

**Screenshots**
<img width="513" alt="Screenshot 2021-11-22 at 22 31 56" src="https://user-images.githubusercontent.com/13930776/142938177-d00e03a3-e9aa-4ff6-b790-451d291f7a94.png">

**Additional Context**
very_good --version
`0.4.10`
flutter --version
```
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (9 weeks ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2
```
Mac M1  12.0.1 Monterey

**Comment by felangel** [comment]
Hi @Hauglid 👋 
Thanks for opening an issue!

This should be resolved by #232 and will be released as part of v0.4.11 shortly 🎉

**Comment by TillitForsikringAS** [comment]
Thanks! 
Absolutely love this starter template! Makes my (coding) life so much easier!

**Comment by Hauglid** [comment]
Hi! 👋 
Thanks for fixing the issue! Looking forward to v0.4.11 💯

**Comment by felangel** [comment]
> Hi! 👋
> Thanks for fixing the issue! Looking forward to v0.4.11 💯

No problem! v0.4.11 is now available 🎉
