### ISSUE TITLE
How to generate a project with custom template?

### ISSUE THREAD

**Issue by thealteria** [VeryGoodOpenSource/very_good_cli#234]
I'm trying to generate a project with my own custom template using `very_good create sample_ppp -t template` command but it's always showing me `is not an allowed value for option "template".` error.

I tried to run `very_good help -t` to know more about the template commant but it's always showing me `Could not find an option or flag "-t".` error. 

Also I tried to check on your website and github but I found nothing regarding the template command and how to use it.

**Comment by felangel** [comment]
Hi @thealteria 👋 
Thanks for opening an issue!

The available templates are `core (default)`, `dart_pkg`, `flutter_pkg`, and `flutter_plugin`.

For example:

`very_good create sample_app -t flutter_pkg`

Let me know if that helps 👍

**Comment by thealteria** [comment]
what if I want to generate the project with my OWN custom template? Can't I do that?

**Comment by marcossevilla** [comment]
hi @thealteria, we use [`package:mason`](https://pub.dev/packages/mason) to create/generate our templates, so if you want to create a custom one, you should probably take a look at that package instead. 👍 

Closing for now as `very_good_cli` doesn't support custom templates, but feel free to check out mason and leave any questions about it on its [GitHub repo](https://github.com/felangel/mason).

**Comment by thealteria** [comment]
OK thanks
