### ISSUE TITLE
fix: Flags for desktop support are not working.

### ISSUE THREAD

**Issue by cvanvlack** [VeryGoodOpenSource/very_good_cli#235]
**Description**
Flags for desktop support are not working.

**Steps To Reproduce**

``` 
> very_good --version                                                                                                                                                         
0.4.11
```

I ran
```
very_good create --project-name=very_good_test --org-name=co.test --desc "Working to figure out everything involved in the very_good template" --android true --ios true --web true --macos true very_good_test
```
and Android, iOS, and Web were created but Macos, Windows and Linux were not. I had to subsequently run 
```
flutter config --enable-macos-desktop
```
to get macos. Similarly, 
```
very_good create --project-name=very_good_test --org-name=co.test --desc "Working to figure out everything involved in the very_good template" very_good_test2
```
did not give desktop support either.

**Expected Behavior**
All of the platforms should be created by default.

**Comment by felangel** [comment]
Just want to add that the reason we don't support desktop is because of lack of flavor support (https://github.com/flutter/flutter/issues/64088)

**Comment by cvanvlack** [comment]
Understood! The output of `very_good create --help` implies otherwise. Can the output help message at least make that clear? I think it's just the help message that makes it look like it's supported unless you are looking at the project readme.
```
very_good create --help
Creates a new very good project in the specified directory.

Usage: very_good create <output directory>
-h, --help                    Print this usage information.
    --project-name            The project name for this new project. This must be a valid dart package name.
    --desc                    The description for this new project.
                              (defaults to "A Very Good Project created by Very Good CLI.")
    --org-name                The organization for this new project.
                              (defaults to "com.example.verygoodcore")
-t, --template                The template used to generate this new project.

          [core] (default)    Generate a Very Good Flutter application.
          [dart_pkg]          Generate a reusable Dart package.
          [flutter_pkg]       Generate a reusable Flutter package.
          [flutter_plugin]    Generate a reusable Flutter plugin.

    --android                 The plugin supports the Android platform.
                              (defaults to "true")
    --ios                     The plugin supports the iOS platform.
                              (defaults to "true")
    --web                     The plugin supports the Web platform.
                              (defaults to "true")
    --linux                   The plugin supports the Linux platform.
                              (defaults to "true")
    --macos                   The plugin supports the macOS platform.
                              (defaults to "true")
    --windows                 The plugin supports the Windows platform.
                              (defaults to "true")

Run "very_good help" to see global options.

```

**Comment by marcossevilla** [comment]
> Understood! The output of `very_good create --help` implies otherwise. Can the output help message at least make that clear? I think it's just the help message that makes it look like it's supported unless you are looking at the project readme.

Oh yeah, but the help message says that the platforms are for the plugin. See:
```
--android                 The plugin supports the Android platform.
                               (defaults to "true")
```
I think that's the default indentation when using the `args` package. @cvanvlack just want to know if the issue is clarified by reading that description for the platform or if you think we could improve that message we're open to suggestions. 🙏

**Comment by cvanvlack** [comment]
Wow, it took me a few read throughs to understand what's going on. The `--android true` flag is only used when using `-t flutter_plugin --android true`?

If that's the case, you may just want to have a few examples that use all the arguments to explain usage. Examples are likely better than descriptions.

I've been relying on the VGV tools/content quite a bit as I've been learning flutter and if the very_good cli is intended to start new users off on the right foot then clarity of use directly with the tool is really helpful.

Otherwise new users might think they're going crazy and can't figure out basic argument lists like I was! 😅

Thanks again for all the work you folks put out. You're rock stars.

**Comment by dev4jam** [comment]
Any changes in supporting Macos on Flutter 3?

**Comment by felangel** [comment]
> Any changes in supporting Macos on Flutter 3?

Unfortunately I believe we’re still blocked on https://github.com/flutter/flutter/issues/64088
