### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by salkhan-ops** [VeryGoodOpenSource/very_good_cli#241]
**Description**
1) I used VeryGoodCli to create flutter app
2) I connected the app with the firestore
3) added the necessary dependencies

it works in production as the app-id or package name is same as in firestore

however, when running the main_development or main_staging, the following error occurs:

Launching lib\main_staging.dart on sdk gphone x86 in debug mode...
**_Running Gradle task 'assembleStagingDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processStagingDebugGoogleServices'.
> No matching client found for package name 'com.techsolo.partydecoclient.stg'_** 

same is the error when using the development except  'com.techsolo.partydecoclient.dev

This means that we have to create three apps with the package names .dev, .stg and the final one without any dot
OR
change the google.jason file and as long as we are doing the development we add .dev in the end of the app-id (i have not tried and i don't think this will work since the id on firestore is unique)

**Comment by felangel** [comment]
Hi @salkhan-ops 👋
Thanks for opening an issue!

I recommend creating a firebase project per flavor. Then you can place the google services configuration in the corresponding flavor directory Android. You can check out
