### ISSUE TITLE
fix: DirectoryGeneratorTarget error: Too many positional arguments: 1 allowed, but 2 found.

### ISSUE THREAD

**Issue by korzonkiee** [VeryGoodOpenSource/very_good_cli#255]
**Description**

```sh
~ very_good --help

Building package executable...
Failed to build very_good_cli:very_good:
.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.4.12/lib/src/commands/create.dart:147:31: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
      DirectoryGeneratorTarget(outputDirectory, _logger),
                              ^
```

**Steps To Reproduce**

1. Activate the newest very_good_cli package: `dart pub global activate very_good_cli 0.4.12`
2. Run: `very_good --help`

**Expected Behavior**
There should be no error.

**Screenshots**
![CleanShot 2022-01-19 at 10 22 39](https://user-images.githubusercontent.com/26259846/150101848-78e0563a-a854-4c33-9b7f-2bd69f91b2d7.png)

**Additional Context**
The error doesn't occur on version `0.4.11`.

**Comment by LastxTemplar** [comment]
getting the same issue.
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```
