### ISSUE TITLE
fix: duplicated android folder on create flutter_plugin 

### ISSUE THREAD

**Issue by erickzanardo** [VeryGoodOpenSource/very_good_cli#267]
**Description**
When creating a new flutter plugin, the `_android` folder gets duplicated in two different places, one is on the root folder (which is the correct place) and another one is on the app-facing package.

**Steps To Reproduce**

1. Run  very_good create -t flutter_plugin bla
2. Check the root folder, there will be a `bla_android`
3. Enter the `bla` folder, there will another `bla_android` here

**Expected Behavior**
The app-facing package shouldn't contain an android folder

**Comment by felangel** [comment]
This should be resolved in [v0.4.17](https://pub.dev/packages/very_good_cli/versions/0.4.17) 🎉
