### ISSUE TITLE
Support for Flutter 2.10.0

### ISSUE THREAD

**Issue by tomassasovsky** [VeryGoodOpenSource/very_good_cli#273]
**Description**
Right now, if you create a flutter app with very_good and try to run it with flutter 2.10, multiple errors appear.

**Steps To Reproduce**

1. Go to terminal
2. Run very_good create my_app
3. Run app on Android Emulator
4. See the error

**Expected Behavior**
The app should launch without errors and warnings

**Additional Context**
Error Nº 1:
![image](https://user-images.githubusercontent.com/63405252/152664976-293c2db1-0792-4efe-a8f6-06455bbeceff.png)

After changing minCompileSdk to 31:
![image](https://user-images.githubusercontent.com/63405252/152664970-d3a95f35-ba24-4f46-b5ec-c54200467b19.png)

After updating kotlin version to 1.6.10:
![image](https://user-images.githubusercontent.com/63405252/152664988-557ab656-7722-4c06-a540-17332f221f6c.png)

**Comment by felangel** [comment]
Hi @tomassasovsky 👋
Thanks for opening an issue and sorry for the inconvenience! Should have an update shortly 👍

**Comment by tomassasovsky** [comment]
Thanks! Big fan of your work, @felangel!

**Comment by felangel** [comment]
@tomassasovsky this should now be resolved in [v0.5.0 of very_good_cli](https://pub.dev/packages/very_good_cli/versions/0.5.0) 🎉 
Thanks for your patience and support! 💙

**Comment by tomassasovsky** [comment]
@felangel awesome, thanks! The app is building now, everything works great. One question though - is there any way to fix these warnings?
![image](https://user-images.githubusercontent.com/63405252/152895270-358b5e02-5d19-4479-a450-9920f0ce2ac2.png)
