### ISSUE TITLE
fix: Unable to create a project

### ISSUE THREAD

**Issue by mateenatupday** [VeryGoodOpenSource/very_good_cli#278]
**Description**
Trying to create a new project and it throws an error of failure as shown below in the screenshot section:

**Steps To Reproduce**
Running the script on the terminal to create a project.

**Current Behavior**
Error while running the command to create a project: `very_good create weather_app --org-name "com.example.www"`

**Screenshots**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/97024248/153002847-d84d5684-fad8-4dc7-bd62-c88f0910b217.png">

**Expected Behavior**

It should create a project.

**Additional Context**
Flutter version:

```
Flutter 2.10.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fdd0af78bb (13 days ago) • 2022-01-25 22:01:33 -0600
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2
```

**Comment by mateenatupday** [comment]
Is it not possible to use the `beta` channel to create a project from CLI?

**Comment by felangel** [comment]
> Is it not possible to use the `beta` channel to create a project from CLI?

Yes it is, but it looks like you are on an older version of the beta channel. Can you try upgrading and then try again?

`flutter upgrade`

**Comment by mateenatupday** [comment]
I'm already on the latest version:
```
mmateen@XIN717584 testapps % flutter --version
Flutter 2.10.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fdd0af78bb (2 weeks ago) • 2022-01-25 22:01:33 -0600
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2
mmateen@XIN717584 testapps % 

```

**Comment by mateenatupday** [comment]
> @mateenatupday is this still an issue?

Hi @felangel, it's fixed now. Thank you.
