### ISSUE TITLE
feat: add support for `test` command

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_cli#279]
As a developer, I want to be able to easily run tests and collect coverage for my projects so that I can identify failing tests and gaps in code coverage.

```sh
# run tests for current project (flutter/dart)
very_good test

# run tests recursively
very_good test --recursive

# run tests for specific project
very_good test ./path/to/my/project

# run tests with coverage generates coverage report at coverage/lcov.info
very_good test --coverage

# run tests with coverage generates coverage report at custom/path/lcov.info
very_good test --coverage --coverage-path ./custom/path

# run tests with coverage and exclude files from coverage
very_good test --coverage --coverage-exclude "*.g.dart"

# run tests with coverage and exit(1) if coverage is below min coverage threshold
very_good test --coverage --min-coverage 100

# run tests with coverage and output coverage results as html report
very_good test --coverage --report html

# run tests with coverage and output coverage results as json output
very_good test --coverage --report json

# run tests without running "pub get" first
very_good test --no-pub

# run tests in a random order
very_good test --test-randomize-ordering-seed random

```

**Comment by orestesgaolin** [comment]
In the context of the https://github.com/VGVentures/employees/discussions/234 I would request for bringing improvement suggested by @jorgecoca to `very_good_cli` along with the `test` command. Long test duration with coverage is one of the major pains across multiple projects and we would be super excited to have a standardized solution to this problem.

**Comment by felangel** [comment]
> In the context of the [VGVentures/employees#234](https://github.com/VGVentures/employees/discussions/234) I would request for bringing improvement suggested by @jorgecoca to `very_good_cli` along with the `test` command. Long test duration with coverage is one of the major pains across multiple projects and we would be super excited to have a standardized solution to this problem.

Yup definitely agree that internal optimizations for test performance should be considered when implementing this 👍

**Comment by definitelyokay** [comment]
Linking to https://github.com/VeryGoodOpenSource/very_good_coverage/issues/20 as it seems relevant to this discussion

**Comment by mtwichel** [comment]
Also adding https://pub.dev/packages/coverde to the discussion - it looks like it supports a lot of the html report generation that this aims to achive, so it may be helpful either as a dependency (although it looks like it would need to expose a lot of its interal logic for that) or just inspiration.

**Comment by marcossevilla** [comment]
> Also adding https://pub.dev/packages/coverde to the discussion - it looks like it supports a lot of the html report generation that this aims to achive, so it may be helpful either as a dependency (although it looks like it would need to expose a lot of its interal logic for that) or just inspiration.

tagging his creator 👉 @mrverdant13

**Comment by felangel** [comment]
There's an early preview of the test command available in [v0.6.0-dev.1](https://pub.dev/packages/very_good_cli/versions/0.6.0-dev.1). It does not include performance optimizations, `min-coverage` or custom reporting yet but we're working on adding that functionality over the course of the next week.

**Comment by felangel** [comment]
:tada [v0.6.0](https://pub.dev/packages/very_good_cli/versions/0.6.0) includes support for:

- running tests with built-in performance optimizations
- running tests recursively in nested packages
- running tests and generating coverage
- running tests and enforcing a minimum coverage threshold
- running tests and excluding files from coverage

We will aim to support generating a coverage report in a subsequent release.

**Comment by davidmartos96** [comment]
> 🎉  [very_good_cli v0.6.0](https://pub.dev/packages/very_good_cli/versions/0.6.0) now includes support for:
> 
> - running tests with built-in performance optimizations
> - running tests recursively in nested packages
> - running tests and generating coverage
> - running tests and enforcing a minimum coverage threshold
> - running tests and excluding files from coverage
> 
> We will aim to support generating a coverage report in a subsequent release.

Nice update! 
I was wondering if you ever thought about supporting the test report generation option from `flutter test` (the --machine option). There are tools like `junitreport` which convert that output into an XML JUnit report, which many CI/CD platforms support to display information about the tests that run (status, duration...).
Let me know if that better fits in a separate issue.

**Comment by felangel** [comment]
@davidmartos96 thanks! It would be great if you could create a separate issue with additional context, thanks!
