### ISSUE TITLE
fix: Check versions before generating new projects

### ISSUE THREAD

**Issue by definitelyokay** [VeryGoodOpenSource/very_good_cli#281]
**Description**

Whenever I am globally using an older version of Flutter which is no longer supported by the CLI tool (using FVM), it is able to generate the project but fails to install packages. It'd be really nice if VG CLI would check to see if the current flutter/sdk version is high enough before generating a package to prevent it from having to stop in the middle of the process.

**Comment by omonare-nybble** [comment]
I agree - having the same issue.

**Comment by jdebecka** [comment]
Would it be possible to add an option to specify the version of flutter when creating the app? At the end of the day `dart fix` should be able to handle the changes between versions. :)

**Comment by felangel** [comment]
After discussing this we've decided not to move forward with this because it will introduce a lot of complexity and instead we've removed the strict flutter version constraint in our templates.

Closing for now but feel free to comment with additional questions.
