### ISSUE TITLE
fix: lint warnings - directives_ordering

### ISSUE THREAD

**Issue by JigneshPatel23** [VeryGoodOpenSource/very_good_cli#293]
**Description**
Lint warnings with the newly created project `directives_ordering`

**Steps To Reproduce**

1. Create a new project 
`very_good create flutter_example`

2. Run Flutter analyzer
`flutter analyze lib test`

3. Observe the console for warnings 

**Expected Behavior**
No warnings

**Screenshots**
<img width="915" alt="Screenshot 2022-02-19 at 8 05 45 PM" src="https://user-images.githubusercontent.com/7347854/154805544-da542219-63d6-41c6-8448-016ba81fa7c2.png">

**Comment by felangel** [comment]
Hi @JigneshPatel23 👋
Thanks for opening an issue!

Did you wait for very_good create to complete before opening the project? very_good create should generate the project, run flutter packages get, and run dart fix —apply. The last step (dart fix) will adjust the import sort order.

**Comment by JigneshPatel23** [comment]
Thanks @felangel, actually while creating the project I got an error on the 2nd step flutter packages to get for the latest flutter version, and hence this dart fix was aborted.
