### ISSUE TITLE
question: app flavor 

### ISSUE THREAD

**Issue by rddewan** [VeryGoodOpenSource/very_good_cli#295]
How can we use it to generate a different flutter flavor ?

**Comment by marcossevilla** [comment]
hi @rddewan 👋 for now, the supported flavors are development, staging and production. if you want to generate a different one, you'll have to do it manually. Hope that helps. 👍

**Comment by rddewan** [comment]
@marcossevilla thank you for your info. Is it possible to add the flavor to existing project or need to create new project?

**Comment by rddewan** [comment]
thanks i mean using the very_good_cli. I have added the flavor manually but unable to change the iOS app name to different flavor

**Comment by felangel** [comment]
> thanks i mean using the very_good_cli. I have added the flavor manually but unable to change the iOS app name to different flavor

Can you provide a bit more information/context? I'm not sure what you mean when you say you're "unable to change the iOS app name to a different flavor".

**Comment by marcossevilla** [comment]
@rddewan you'll need to tweak native configurations to do that. this is the [android way](https://stackoverflow.com/a/30879430) and the [ios way](https://medium.com/swift2go/different-app-display-name-based-on-xcode-scheme-d709307d0c01).

Let me know if that helps. 👍

**Comment by rddewan** [comment]
thank you let me try it out

**Comment by felangel** [comment]
Closing for now but feel free to comment with any follow-up questions and we're happy to continue the conversation 👍
