### ISSUE TITLE
fix: ignore .fvm directory when searching for pubspec files

### ISSUE THREAD

**Issue by Limbou** [VeryGoodOpenSource/very_good_cli#306]
**Description**
Currently when running `very_good packages get --recursive` all the packages from `.fvm` folder are also targeted. I believe we want to avoid that for two reasons:

1. It could take quite a lot of time to run this command for all packages inside `.fvm`
2. It is unnecessary pretty much, we only need to run this command for packages used inside of the project

**Steps To Reproduce**

1. Go to your Flutter project directory
2. Start using `fvm` there, for example: `fvm use 2.10.3`
3. Run `very_good packages get --recursive`
4. See the command being run for packages inside `.fvm` folder

**Expected Behavior**
The command should be run only for packages actually used inside  project.

**Comment by l-borkowski** [comment]
Bumping this up, cause having the same issue 
![image](https://user-images.githubusercontent.com/79083099/157284333-67bd81bf-a5fd-4faf-801f-71958011d8bd.png)
