### ISSUE TITLE
New Flutter Projects is not created with custom domain.

### ISSUE THREAD

**Issue by Prashant4900** [VeryGoodOpenSource/very_good_cli#315]
**Description**
I tried to create a new flutter project with custom --org-name and it's created well without issue but when I tried to run its show the error and the program are terminated.

Commands:
1. very_good create second --org-name "in.smallhub" => created, not run
2. very_good create second --org-name in.smallhub => created, not run
3. very_good create --org-name "in.smallhub" thrid => created, not run
4. very_good create --org-name in.smallhub forth => created, not run
5. very_good create second => created, run

**Steps To Reproduce**

1. Update Flutter & very_good_cli to latest version
6. Create new projects with custom --org-name: "com.example"/ com.example
7. Run the projects on Android Emulator
8. See an error

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62440911/158636694-9aa8b89a-6ec6-438a-ae83-5a0b606659e0.png)

![image](https://user-images.githubusercontent.com/62440911/158637971-05b1bdac-0d23-478e-8c91-b4006e9df7cb.png)

![image](https://user-images.githubusercontent.com/62440911/158636569-e117b24c-6a1a-43f3-ac73-a4679248428c.png)

![image](https://user-images.githubusercontent.com/62440911/158636830-4076b8e6-82fc-4593-b44a-6b49cc49d7ff.png)

**Additional Context**

**Comment by felangel** [comment]
Hi @Prashant4900 👋 
Thanks for opening an issue!

This is because `in` is a keyword in Kotlin. See https://github.com/flutter/flutter/issues/42519#issuecomment-570189646
