### ISSUE TITLE
Proper directories structure are not show in android studio.

### ISSUE THREAD

**Issue by Prashant4900** [VeryGoodOpenSource/very_good_cli#324]
### **Description**
recently when I open my very_good projects on the android studio I don't see a complete directories structure there It shows only files not show folders even I tried to downgrade my very_good_cli version as well from 0.6.0 to 0.5.5 but nothing happen. but after that, I created new projects in the normal way and open in the android studio it worked fine.

### **Steps To Reproduce**

1. Install very_good_cli on windows (not tried in Linux or MasOS)
2. create new projects with custom --org-name
3. open in android studio

### **Expected Behavior**
its need to show the proper directories structure like vs-code.

### **Screenshots**
**very_good_cli --org-name vs flutter**
![image](https://user-images.githubusercontent.com/62440911/159065038-462394ed-eddd-4c4d-95de-b0e61506fc90.png)

**very_good_cli --org-name vs very_good_cli**
![image](https://user-images.githubusercontent.com/62440911/159067680-aa0f3a65-31a0-48b1-ad93-bfa266ca341a.png)

**Comment by felangel** [comment]
Hi @Prashant4900 👋 
Thanks for opening an issue!

I just want to make sure I understand correctly, are the files/folders there when you open the project in VSCode? If so, can you provide a screen recording that illustrates how you're opening the project in Android Studio? Thanks!

**Comment by Prashant4900** [comment]
> Hi @Prashant4900 👋 Thanks for opening an issue!
> 
> I just want to make sure I understand correctly, are the files/folders there when you open the project in VSCode? If so, can you provide a screen recording that illustrates how you're opening the project in Android Studio? Thanks!

yes, its shown in vs-code. My system is not that powerful so I don't think it's possible to make recording. but in the end, when we use vs-code there is no problem but in the android studio, if we create a project without --org-name then it's fine otherwise that problem occure.

**Comment by felangel** [comment]
> > Hi @Prashant4900 👋 Thanks for opening an issue!
> > I just want to make sure I understand correctly, are the files/folders there when you open the project in VSCode? If so, can you provide a screen recording that illustrates how you're opening the project in Android Studio? Thanks!
> 
> yes, its shown in vs-code. My system is not that powerful so I don't think it's possible to make recording. but in the end, when we use vs-code there is no problem but in the android studio, if we create a project without --org-name then it's fine otherwise that problem occure.

What are you specifying as the `--org-name`? Can you provide detailed reproduction steps or a link to a minimal reproduction sample on GitHub? Thanks!

**Comment by Prashant4900** [comment]
> > > Hi @Prashant4900 👋 Thanks for opening an issue!
> > > I just want to make sure I understand correctly, are the files/folders there when you open the project in VSCode? If so, can you provide a screen recording that illustrates how you're opening the project in Android Studio? Thanks!
> > 
> > 
> > yes, its shown in vs-code. My system is not that powerful so I don't think it's possible to make recording. but in the end, when we use vs-code there is no problem but in the android studio, if we create a project without --org-name then it's fine otherwise that problem occure.
> 
> What are you specifying as the `--org-name`? Can you provide detailed reproduction steps or a link to a minimal reproduction sample on GitHub? Thanks!

I just record the [video ](https://youtu.be/8UCn5N7N0JI)and doesn't know how this happen but this time it work properly when I try the same thing yesterday even more than 5 times it give the same response every time as you see in the above images and I don't know this fixed in temporary or permanent.

Note: Initially my very_good_cli version was on 0.6.0 but because of this error I downgrade its top 0.5.5 and android studio initially have 7-8 months old but I update it also to the latest version but nothing happen.
