### ISSUE TITLE
fix: Collect usage statistic showing twice

### ISSUE THREAD

**Issue by wolfenrain** [VeryGoodOpenSource/very_good_cli#328]
**Description**
When running the `very_good_cli` for the first time it asks if it can collect usage statistics. If you say `y`es then it will output the exact message once more.

**Steps To Reproduce**

1. Install the `very_good_cli` from clean (tested it with v0.6.0)
2. Run a `very_good create` command
3. When asked if it can collect data say `y`es.
4. It outputs the same message again and continues.

**Expected Behavior**
That it will only show the message asking to collect data once, before answering and not again after answering the question.

**Screenshots**
![image](https://user-images.githubusercontent.com/15887627/159348060-4c22b9e1-3dbe-4cb8-905e-8a55b5b32350.png)

**Additional Context**
I did run it on dart version `2.15.1` by accident but I was able to reproduce it after updating and clean installing the tool.

- Terminal: bash v5.1.8
- OS: pop-os 21.10

**Comment by felangel** [comment]
Hi @wolfenrain 👋 
Thanks for opening an issue!

Are you able to provide more context regarding what OS you're running on? Also, can you confirm that other commands only execute once? The reason I ask is because there have been similar issues reported like https://github.com/leoafarias/fvm/issues/227 and https://github.com/VeryGoodOpenSource/very_good_cli/issues/121.

**Comment by wolfenrain** [comment]
> Hi @wolfenrain wave Thanks for opening an issue!
> 
> Are you able to provide more context regarding what OS you're running on? Also, can you confirm that other commands only execute once? The reason I ask is because there have been similar issues reported like [leoafarias/fvm#227](https://github.com/leoafarias/fvm/issues/227) and #121.

The commend itself ran only once, it also only happened after I gave an answer.

I am currently running it on Linux, pop-os 21.10

**Comment by wolfenrain** [comment]
So I managed to reproduce this inside a Docker container, while that obviously does not fully reflect any working environment the problem itself is consistent on my Linux machine so I suspect this is a Linux + Bash problem? 

Might still be a problem specific to the terminal emulator that is being used, can't test that right now.

1. Run `docker run -ti dart:2.16.1 /bin/bash` to start a container with Dart v2.16.1 and with bash as the shell. PS: I did test other versions of Dart as well and they all resulted in the same outcome.
2. Install the CLI: `dart pub global activate very_good_cli`
3. The container does not have proper PATH variables for Dart so just run it from the cache: `.pub-cache/bin/very_good`
4. The question pops up, press `y` and enter.
5. The question pops up again, so it now shown twice and the answer you gave is below that. Rest works as expected the `help` is visible.

**Comment by wolfenrain** [comment]
> Might still be a problem specific to the terminal emulator that is being used, can't test that right now.

This is no uncertain, I have followed these steps on my intel macbook and got exactly the same results. So either the stdout writing is going haywire (based on a quick assessment of the code for this I would assume that it is not the case) or the CLI and Bash/Linux aren't the greatest friends (yet).

**Comment by wolfenrain** [comment]
Based on this [method](https://github.com/felangel/mason/blob/727ff266afb7c8722700d0d67a46155639d023b5/packages/mason_logger/lib/src/mason_logger.dart#L180) I wrote up a simple test file to see if the problem is reproducible in a simplere case.

The test I wrote up ran in a Docker VM on Dart 2.16.1, I initially just used the stdout and stdin from `dart:io`:
```dart
import 'dart:io';

void main() {
  const message = 'testing this';
  stdout.write(message);

  stdin.readLineSync()?.trim();

  stdout.writeln('\x1b[A\u001B[2K$message with result');
}
```

This does not result in the problem describe above. So I took a quick look at the universal_io, expected it to just reexport `dart:io` but it seems they have their [own implementation](https://github.com/dint-dev/universal_io/blob/master/lib/src/io/stdio.dart) of stdio, and it seems to be a full copy, based on the license at the top, from the dart stdio one.

So considering that it is working without universal_io as expected I suspect the problem might lie somewhere in their implementation.

**Comment by wolfenrain** [comment]
> > Based on this [method](https://github.com/felangel/mason/blob/727ff266afb7c8722700d0d67a46155639d023b5/packages/mason_logger/lib/src/mason_logger.dart#L180) I wrote up a simple test file to see if the problem is reproducible in a simplere case.
> > The test I wrote up ran in a Docker VM on Dart 2.16.1, I initially just used the stdout and stdin from `dart:io`:
> > ```dart
> > import 'dart:io';
> > 
> > void main() {
> >   const message = 'testing this';
> >   stdout.write(message);
> > 
> >   stdin.readLineSync()?.trim();
> > 
> >   stdout.writeln('\x1b[A\u001B[2K$message with result');
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This does not result in the problem describe above. So I took a quick look at the universal_io, expected it to just reexport `dart:io` but it seems they have their [own implementation](https://github.com/dint-dev/universal_io/blob/master/lib/src/io/stdio.dart) of stdio, and it seems to be a full copy, based on the license at the top, from the dart stdio one.
> > So considering that it is working without universal_io as expected I suspect the problem might lie somewhere in their implementation.
> 
> Hmm that's interesting! Thanks for looking into it. Are you planning to try swapping out `dart:io` with `universal_io` in your example to see if you're able to reproduce?

Yes I already tried, but it was throwing some `segmentation` errors when I tried to run the file in Docker 😅 , but I can give it another go later today.

**Comment by felangel** [comment]
This should be resolved now. Developers should be able to just re-activate `very_good_cli` to get the latest release of `package:mason_logger` which includes the fix 🎉
