### ISSUE TITLE
fix: Collect usage statistic question not showing again after if the command gets "killed"

### ISSUE THREAD

**Issue by wolfenrain** [VeryGoodOpenSource/very_good_cli#332]
**Description**
I am not entirely sure if this is a "bug" but if I run the `very_good` command in a clean environment and stop (CTRL+C, CMD+C) the command without answering the collect usage statistic question it will never ask me again.

This might not be a bug as it might just assume "no" and I know I can toggle it using the `--analytics` flag but from a user experience I am now left in the dark in what it does.

**Steps To Reproduce**

1. Install the `very_good_cli` from clean (tested it with v0.6.0)
2. Run a `very_good` command
3. Kill the process without answering the collect usage statistic question
4. Run a `very_good` command again, it won't ask again

**Expected Behavior**
I expected that it would ask me again considering I did not explicitly answer with a `y`es or `n`o. So right now I am not sure if it is collecting data or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/15887627/159530707-436dc8b6-d750-4127-8278-0e945c4ec2d2.png)

**Additional Context**
NVT

**Comment by tomarra** [comment]
This analytics request has been removed from the tool so this ticket no longer is relevant. Closing as "no action needed"
