### ISSUE TITLE
feat: add `--offline` flag in `create` command

### ISSUE THREAD

**Issue by yeikel16** [VeryGoodOpenSource/very_good_cli#352]
**Description**
In some cases I do not have the network available to create a project with the client, it needs to download several dependencies. It would be very helpful to make use of the [caching system](https://dart.dev/tools/pub/cmd/pub-get#the-system-package-cache) available in the environment variable [PUB_CACHE](https://dart.dev/tools/pub/environment-variables) by using the `--offline` flag when creating both a project like packages or some plugin.

I would like to work on this feature if possible.

**Comment by tomarra** [comment]
Hi @yeikel16 thanks for the suggestion. Given that there hasn't been any activity on this ticket in over a year and this isn't a use case we are prioritizing as its not a situation we find many users in I'm going to be closing this as "won't fix". That being said, if you would like to work on a fix for this and open a PR the team would be able to work with you on getting it merged in.
