### ISSUE TITLE
Github Action should run test --recursive to include packages

### ISSUE THREAD

**Issue by przbadu** [VeryGoodOpenSource/very_good_cli#354]
**Description**

If you create `packages/package-name`, it will have independent tests for this package alone. Very good cli should run test recursively in github action to include all testcases from main repo as well as from repos like `packages`.

**Steps To Reproduce**

1. Generate new flutter project with `very_good` cli
2. Generate package for the project with `very_good create packages/test_lib -t dart_pkg` which will generate `packages/test_lib`  inside main project
3. Write some random testcase inside test_lib/test, specially write failing test case
4. commit and push the code
5. Check github action and verify, everything passes.

**Expected Behavior**

- If you run tests locally using `very_good test --recursive` you will see 1 testcase fail, and it should fail in github action as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/4189129/161475284-cb58c9d8-a9dc-4c93-870f-d8ebafbeb8d1.png)

![image](https://user-images.githubusercontent.com/4189129/161474698-ae56fead-a871-43e4-a842-8d6412be586a.png)

**Additional Context**

- If https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/.github/workflows/very_good_cli.yaml#L43 is the template for githubaction, then there is no `--recursive` or `-r` flag in testcase.

Kindly guide me if I am missing something here.

**Comment by felangel** [comment]
Hi @przbadu 👋 
Thanks for opening an issue!

Are you referring to the [Very Good Workflows](https://github.com/verygoodopensource/very_good_workflows) GitHub Action?

**Comment by przbadu** [comment]
Hey @felangel thank you for the quick response 😃 . Yes that issue is related with https://github.com/verygoodopensource/very_good_workflows. Should I file this ticket over there?

**Comment by felangel** [comment]
> Hey @felangel thank you for the quick response 😃 . Yes that issue is related with https://github.com/verygoodopensource/very_good_workflows. Should I file this ticket over there?

Yes that would be great, thanks!

**Comment by przbadu** [comment]
Done, thank you
