### ISSUE TITLE
feat: use swift for ios on flutter_plugin

### ISSUE THREAD

**Issue by Adherentman** [VeryGoodOpenSource/very_good_cli#370]
**Description**
very_good create flutter_plugin ios is oc,how to create swift for ios？

**Expected Behavior**
ios plugin use swift

**Comment by marcossevilla** [comment]
hi @Adherentman 👋  currently the flutter_plugin template uses Objective-C, thanks for bringing this up, we'll update this issue when we migrate to Swift, for now it's not supported 👍

**Comment by Adherentman** [comment]
Now I refer to flutter's swift plugin to manually configure，Thanks

**Comment by marcossevilla** [comment]
@Adherentman I don't think I understand correctly, you want to use Swift with the default flutter plugin template? I suggest you take a look at the [official docs](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#plugin-platforms) if that's your question

**Comment by renancaraujo** [comment]
Details on what should be done: 
The template resides on [very_good_flutter_plugin](https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/), so the platform implementation for macos and ios should be changed there. Then the generated brick should be bundled [here](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/commands/create/templates/flutter_plugin/flutter_plugin_bundle.dart).
