### ISSUE TITLE
feat: prettify the test output by listing failed tests

### ISSUE THREAD

**Issue by orestesgaolin** [VeryGoodOpenSource/very_good_cli#377]
**Description**
Currently, especially on CI, it's difficult to understand which tests have failed without scrolling through the output. I'd love to see a summary of failed tests in some concise form aside from the typical output. Usually I'm going to rerun them anyway in my IDE to see what exactly failed.

**Current output**
![screenshot_2022-05-06_14 26 35](https://user-images.githubusercontent.com/16854239/167131116-84993b88-b7f2-4e60-ac05-db39c1651590.png)

And at the end:

```
00:44 +923 -1 ~1: Some tests failed.
```

**Expected Behavior**

```
00:44 +923 -1 ~1: Some tests failed.
Failed tests:
  - test/compare_video/view/compare_video_page_test.dart:237:59 (adds MyVideosRequested to myVideosBloc on pull to refresh on my videos tab)
  - ...
```

**Comment by renancaraujo** [comment]
Closed on #397
