### ISSUE TITLE
fix: Running tests locally may timeout

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_cli#386]
**Description**
Just after cloning the repository, running `flutter_cli_test` via  `flutter pub run test test/src/cli/flutter_cli_test.dart` may make the test timeout fail if the user doesnt answer to the git prompt.

We should either add a timeout to the command (if possible) or advise for this on contributing.md

**Comment by tomarra** [comment]
Notes from prioritization meeting.

- This should be fixed already
- @tomarra to follow CONTRIBUTING guide to setup environment and confirm that this no longer happens.

**Comment by tomarra** [comment]
Was able to clone a fresh copy of the repo, get dependencies setup, and run `flutter pub run test test/src/cli/flutter_cli_test.dart` without issue. Confirms this is fixed. Closing as "won't fix"
