### ISSUE TITLE
feat: skip folder in recursive task somehow

### ISSUE THREAD

**Issue by ffgiraldez** [VeryGoodOpenSource/very_good_cli#395]
**Description**
Hi thanks for this awesome tool, recently I started to use [flutter_wrapper](https://github.com/passsy/flutter_wrapper) to link projects with specific flutter version and notice that if I invoke something recursively it launch also projects inside flutter wrapper,
```
✓ Running "flutter packages get" in ~/projects/sample/.flutter/bin/cache/dart-sdk/lib/_internal/js_runtime (1s)
✓ Running "flutter packages get" in ~/projects/sample/.flutter/bin/cache/dart-sdk/lib/_internal/sdk_library_metadata (1s)
✓ Running "flutter packages get" in ~/projects/sample/.flutter/bin/cache/pkg/sky_engine (1s)
✓ Running "flutter packages get" in ~/projects/sample/.flutter/examples/splash (1s)
```
**Steps To Reproduce**

1. very_good create my_app --desc "My new Flutter app"
2. install flutter_wrapper following instruction in it repository
3. very_good packages get --recursive   

**Expected Behavior**
add a way to skip that folder or any other I configure

**Comment by marcossevilla** [comment]
hi @ffgiraldez 👋 we currently don't support flutter_wrapper, until we add that `.flutter` folder to the ignored files from the CLI, I suggest you use [fvm](https://fvm.app/) if this issue is blocking you, thanks for opening the issue!
