### ISSUE TITLE
fix: Please add way to work from pipelines without analysis

### ISSUE THREAD

**Issue by hryhoriiziahunepam** [VeryGoodOpenSource/very_good_cli#396]
**Description**
I just try to addd CI/CD with very_good
I know about very_good --analytics false
But this aks about analytics on first time

and my try to skip this step not helps ((sleep 3; echo y) | very_good test --coverage)
can you please add possibility run without asking use or not to use analytics?

here is by example of pipelines, thanks! 

      #      - task: Bash@3
      #        displayName: "Run unit tests with coverage"
      #        inputs:
      #          targetType: 'inline'
      #          script: |
      #            export PATH="$PATH":"$HOME/.pub-cache/bin"
      #            export PATH="$PATH":"$HOME/hostedtoolcache/Flutter/$(FlutterVersion)-stable/macos/flutter/.pub-cache/bin"
      #            export PATH="$PATH":"$HOME/hostedtoolcache/Flutter/$(FlutterVersion)-stable/macos/flutter/bin/cache/dart-sdk/bin"
      #            (sleep 3; echo y) | very_good test --coverage

**Comment by Maatteogekko** [comment]
this worked for me, but yeah, an option to make this work out of the box would be handy
```
yes | flutter pub run very_good_cli:very_good &&

flutter pub run very_good_cli:very_good test --coverage
```

**Comment by hryhoriiziahunepam** [comment]
> this worked for me, but yeah, an option to make it work out of the box would be handy
> 
> ```
> yes | flutter pub run very_good_cli:very_good &&
> 
> flutter pub run very_good_cli:very_good test --coverage
> ```

thanks, actually this is help me, so we can close this question

**Comment by Maatteogekko** [comment]
> ```
> yes | flutter pub run very_good_cli:very_good &&
> 
> flutter pub run very_good_cli:very_good test --coverage
> ```

This does no longer work on latest flutter stable release (3.7)

Another workaround is to create the config files from which the CLI reads whether it is the first start.
Add the following to your job
```yaml
before_script:
    - "echo '{ \"firstRun\": false, \"enabled\": false }' > $HOME/.very-good-cli"
```
Then you can just use `flutter pub run very_good_cli:very_good test --coverage` directly
