### ISSUE TITLE
Unable to build flavored web bundle

### ISSUE THREAD

**Issue by githubmonkey** [VeryGoodOpenSource/very_good_cli#403]
**Description**
Option 'flavor' is not recognized when building for web. How do I build for hosting on flavored firebase projects? 

**Steps To Reproduce**

➜  ~/StudioProjects very_good create foobar
✓ Generated 239 file(s) (0.2s)
✓ Running "flutter packages get" in foobar (2.7s)
✓ Running "dart fix --apply" in foobar (11.3s)

Created a Very Good App! 🦄

+----------------------------------------------------+
| Looking for more features?                         |
| We have an enterprise-grade solution for companies |
| called Very Good Start.                            |
|                                                    |
| For more info visit:                               |
| https://verygood.ventures/solution/very-good-start |
+----------------------------------------------------+
➜  ~/StudioProjects cd foobar 
➜  ~/StudioProjects/foobar **flutter build web --flavor production --target lib/main_production.dart**
**Could not find an option named "flavor".**

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

flutter build web --target lib/main_production.dart --flavor production --release

**Expected Behavior**
I would have expected to create different build directories for each flavor, which I can then deploy to the different hosting sites. 

**Screenshots**

**Additional Context**
I first noticed the problem with flutter 2.5 but upgrading to FLutter 3.0 and very_good to 0.7.2 made no difference

**Comment by felangel** [comment]
Hi @githubmonkey 👋 
Thanks for opening an issue!

Web doesn't have a concept of flavors so you can just specify the target without the flavor when doing a build:

```sh
flutter build web --target lib/main_production --release
```

Let me know if that helps 👍

**Comment by githubmonkey** [comment]
I had tried but ran into problems delpoying the targeted build. However, I now found that the problem was with my firebase.json config. It contained a site parameter which meant that I couldn't deploy my targeted builds into the other "flavored" hosting sites. 

I now removed the site param from my firebase.json and all is well. Thanks.

**Comment by enqvida** [comment]
Please add this little nugget in the readme :)
