### ISSUE TITLE
fix: `flutter_plugin` template generates all platforms no matter the platform flag used

### ISSUE THREAD

**Issue by wolfenrain** [VeryGoodOpenSource/very_good_cli#424]
**Description**

As a developer I can create a `flutter_plugin` template using the CLI and pass which platforms I dont want using the `--<platform_name> false` option. This works as expected but the example generated for the plugin will still contain all platforms.

**Steps To Reproduce**

1. Run `very_good create my_plugin -t flutter_plugin --ios false`
2. Check the `my_plugin/my_plugin/example` directory, it will contain an iOS dir.

**Expected Behavior**

That the generated example only has the platforms that I require for my plugin.

**Comment by dewinjm** [comment]
The same goes with ```.github/workflows/``` files.

When run for example ```very_good create abc_plugin -t flutter_plugin --web false --windows false --macos false --linux false```

The workflows directory contains all platforms template and keep my_plugin files even though the plugin name is abc_plugin:

![screenshot](https://user-images.githubusercontent.com/2231387/177859388-5dfbe65a-ebc9-4a1d-b39f-ec57160cc360.png)

I see this file  [flutter_plugin_bundle.dart](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/commands/create/templates/flutter_plugin/flutter_plugin_bundle.dart) has the workflows static path. "my_plugin.yaml, my_plugin_android.yaml, ..."

**Comment by wolfenrain** [comment]
Change the template project to reflect the above mentioned changes: https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/pull/41
