### ISSUE TITLE
Support for Flutter Version Management

### ISSUE THREAD

**Issue by moshOntong-IT** [VeryGoodOpenSource/very_good_cli#426]
Does the very_good_cli have feature about flutter version management? if it doesn't can you add this feature.

**Comment by felangel** [comment]
Hi @moshOntong-IT 👋
Thanks for opening an issue!

Can you provide some context regarding what you mean by Flutter version management? Are you referring to capabilities that tools like fvm offer?

**Comment by moshOntong-IT** [comment]
Yes it something like the capabilities of fvm offer

**Comment by felangel** [comment]
@moshOntong-IT what would be the advantage in your opinion? We definitely don't want to reimplement the same functionality when developers can just use fvm.

**Comment by mugbug** [comment]
Hey y'all 👋 

@moshOntong-IT, maybe this issue I just added can help you out: https://github.com/VeryGoodOpenSource/very_good_cli/issues/439.
