### ISSUE TITLE
Retrieve bricks for "create" from remote source (aka do not include bundles in the codebase)

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_cli#442]
Today we include the bundles for each "very_good create" template as dart bundles in the codebase. These bundles are often generated from bricks that live in different repositories. 

To  easy the effort of updating these bricks and improve the quality of life of contributors, we shall retrieve the bundles in runtime from either brickhub or git repositores, making it clear the where these bundles come from.

The goal is to update templates without having to push new versions of Very Good CLI

Phase 1:
Publish to Brickhub
- [x] Dart CLI - Needs to be done _After_ the verbose flag issue (https://github.com/VeryGoodOpenSource/very_good_dart_cli/issues/18)
- [x] Flutter Plugin
- [x] Very Good Core

Phase 2:
- [ ] Update CLI to support downloading templates from remote registry

Phase 3:
- [ ] Upgrade and cache logic - Check for newer or nonbreaking versions, otherwise use the cached version.

**Comment by BeatriceMitchell** [comment]
Unblocked, as we now have access to some publishing accounts that we can use
