### ISSUE TITLE
fix: This requires the 'super-parameters' language feature to be enabled.

### ISSUE THREAD

**Issue by askHarshV** [VeryGoodOpenSource/very_good_cli#460]
**Description**
Getting errors *This requires the 'super-parameters' language feature to be enabled* on very_good create app1

I am on latest flutter channel master and have done the flutter upgrade.
current version
Flutter 3.1.0-0.0.pre.1615 • channel master • https://github.com/flutter/flutter.git
Framework • revision faabe2b6e5 (2 hours ago) • 2022-07-12 06:05:07 -0400
Engine • revision 2ee0b934b9
Tools • Dart 2.18.0 (build 2.18.0-271.0.dev) • DevTools 2.15.0

**Steps To Reproduce**

1. very_good create app1
2. in app.dart, super.key gives the error This requires the 'super-parameters' language feature to be enabled.
3. Also i10n.dart has errors like Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'.

**Expected Behavior**
clean working starter app on very_good create app1

**Additional Context**
running all this on windows environment

**Comment by renancaraujo** [comment]
Depending on the version of very_good_cli you have installed you may have to adjust the created sample if you are using an old version fo flutter (which is your case). What is the very_good_cli version you are using?

**Comment by wolfenrain** [comment]
Closing this as the above comment would solve your issue, or updating your flutter version would work as well.
