### ISSUE TITLE
fix: generate a `CHANGELOG.md` for the `dart_pkg` and `flutter_pkg` templates

### ISSUE THREAD

**Issue by Luckey-Elijah** [VeryGoodOpenSource/very_good_cli#468]
**Description**

[`dart.dev`](https://dart.dev/guides/libraries/create-library-packages#providing-additional-files) recommends packages have a `CHANGELOG.md` when uploaded to [`pub.dev`](https://pub.dev/). 

I'm suggesting `very_good create -t flutter_pkg <name>` and `very_good create -t dart_pkg <name>` should both create `CHANGELOG.md` files.

`dart create <name>` generates a `CHANGELOG.md`:
```md
## 1.0.0

- Initial version.
```

**Comment by felangel** [comment]
Hi @Luckey-Elijah 👋 
Thanks for opening an issue!

We're working on revamping the Dart and Flutter package templates and they will include a CHANGELOG (among many other improvements in the near future). Thanks again and sorry for any inconvenience!

**Comment by Luckey-Elijah** [comment]
Sounds great! Looking forward to your _very good_ changes 🙂

**Comment by Luckey-Elijah** [comment]
PS 
I did notice #385 but I'm not sure if they're quite duplicates. That one is requesting a full-featured changelog configuration tool. I'd just like to see the file created 🙂

**Comment by renancaraujo** [comment]
This was fixed by #592
