### ISSUE TITLE
Flavor Commands

### ISSUE THREAD

**Issue by tyypgzl** [VeryGoodOpenSource/very_good_cli#476]
How can I customize flavors? for example to continue the project with a flavor or two. Can you provide more information about the CLI commands?

**Comment by felangel** [comment]
Hey @tyypgzl 👋 
Thanks for opening an issue!

Can you please clarify whether you are asking to generate custom flavors via the CLI or are just looking for documentation around managing flavors? Thanks!

**Comment by tyypgzl** [comment]
Hi @felangel  🤙
I want to open a new project without flavor or I want to create a project with 2 flavors. Actually, I want to know the answer to 2 questions. 🤓

**Comment by alestiago** [comment]
Hi @tyypgzl , I personally think this is a valid request. I'm closing this issue in favour of #680, feel free to 👍 that issue instead.
