### ISSUE TITLE
fix: Can't replace very_good_cli generated app icon

### ISSUE THREAD

**Issue by CartmanGD** [VeryGoodOpenSource/very_good_cli#485]
I have generated my Flutter app using [very_good_cli][1].

I'm using [flutter_launcher_icon][2] to change the default app icon.

I make sure that the old icon does not exist in the project, but still, the `very_good_cli` icon appears after reinstalling the app.

[![enter image description here][3]][3]

Where does it get this icon if it does not exist in the project? 

**What are the steps I need to take to change the app's icon that was generated by `very_good_cli`?**

  [1]: https://pub.dev/packages/very_good_cli
  [2]: https://pub.dev/packages/flutter_launcher_icons
  [3]: https://i.stack.imgur.com/PI3rL.png

**Comment by rajarshi-ch** [comment]
I have a similar issue with the splash screen, where I don't really know how to change the splash screen Drawable to something custom. Any leads on that @CartmanGD ?

**Comment by saveKenny** [comment]
Using [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) screen worked for me. However I didn't tested it with different flavors.

**Comment by k1ycee** [comment]
Experiencing this same issue but only on android

**Comment by felangel** [comment]
You may also need to uninstall and reinstall the app or restart the emulator as sometimes assets can get cached.

**Comment by k1ycee** [comment]
So I checked and I realized that my `mipmap-anydpi-v26` had the initial svg icon, so apparently I still had the icon and my device was building to that icon instead.
So if you have the issue it's probably coming from this folder.

**Comment by felangel** [comment]
Going to close this for now since there aren't any actionable next steps on your end. Feel free to comment with any follow-up questions and we can continue the conversation 👍

**Comment by CartmanGD** [comment]
> @CartmanGD were you able to fix the issue with the responses above?

Yes, @k1ycee comment was really helpful. Thanks guys!
