### ISSUE TITLE
Remove Default Splash Screen 

### ISSUE THREAD

**Issue by NurRozikin** [VeryGoodOpenSource/very_good_cli#486]
How to remove default splash screen?
Thx

**Comment by NurRozikin** [comment]
Resolve this problem using flutter_native_splash

**Comment by JakeHadley** [comment]
@NurRozikin how did you solve this? I ran everything with flutter_native_splash and it's still briefly showing the original VGV splash image.

**Comment by NurRozikin** [comment]
Sorry, It was from flutter_launcher_icons, not from flutter_native_splash.

**Comment by trueshail** [comment]
@JakeHadley Did it work for you? I am still seeing the original VGV splash image.

**Comment by JakeHadley** [comment]
> @JakeHadley Did it work for you? I am still seeing the original VGV splash image.

Yeah I just had to restart everything and it worked.

**Comment by osamamohammed98** [comment]
not work with my 
flutter_launcher_icons
flutter_native_splash

**Comment by iamnabink** [comment]
Facing a similar issue, [is it because of flutter_launcher_icons? ] but not working, any fixes yet?
