### ISSUE TITLE
Exclude from coverage not removing file

### ISSUE THREAD

**Issue by rodrigobastosv** [VeryGoodOpenSource/very_good_cli#496]
First of all thanks for the brilliant work!

I am having a hard time trying to exclude files from the coverage report. I have a file called `fake_local_storage_service.dart` and i cant remove it from coverage report.

The command i am running is: `very_good test --coverage --exclude-coverage fake_local_storage_service.dart`

The command runs fine, but the file is not removed from the coverage. I tried a lot of variations like using single or double quotes.

So is this syntax correct? What am i doing wrong?

Another question would be: let's say i want to remove all files that had service on the filename.

Would the command be `very_good test --coverage --exclude-coverage *_service.dart` ?

I am not very used with glob syntax, so i do not know if its my mistake or if it's just not working.

**Comment by erickzanardo** [comment]
Hey 👋

I believe your glob is incorrect, can you test if the following will work?

`very_good test --coverage --exclude-coverage **/*_service.dart`

**Comment by rodrigobastosv** [comment]
@erickzanardo thanks for you reply, but that didn't work.

You can see on this image above that the report was generated with that service file (and others).

<img width="1785" alt="Screen Shot 2022-09-22 at 11 33 33" src="https://user-images.githubusercontent.com/12686272/191775780-604b1aa0-dd4e-4a81-aec1-589068b047ae.png">

**Comment by erickzanardo** [comment]
Oh, alright! So, when tests with coverage collection is run, the command will generate the lcov files for all files.

the `--exclude-coverage` flag will not change those files, it will only skip the matched files when creating its total coverage. So your file was probably not accounted for the `very_good` command total coverage, but since the html was generated from the lcov files, it shows up there.

**Comment by rodrigobastosv** [comment]
Got it! That kind of makes sense. Thanks very much @erickzanardo.

Can i ask one more thing please? How do i specify multiple blobs?

**Comment by erickzanardo** [comment]
Sure, you can do `{...,...}`.

Check the readme of the package that we use for glob resolution, maybe the docs there can help you with more different patterns

https://pub.dev/packages/glob

**Comment by rodrigobastosv** [comment]
Thank you! That's exactly what i was looking form

**Comment by mrgnhnt96** [comment]
@rodrigobastosv 

What you're looking for is to update the lcov.info file. You can do this by running this script

```console
lcov --remove coverage/lcov.info '**/*_service.dart' -o coverage/lcov.info
```

@felangel, @erickzanardo
Maybe we could include this in the `very_good test` script, using the `--exclude-coverage` glob?
