### ISSUE TITLE
Tests Passing using Flutter test but failing using very_good test

### ISSUE THREAD

**Issue by ShivamMattoo33** [VeryGoodOpenSource/very_good_cli#497]
Hello,

I recently came across this package and wanted to use it to get flutter test coverages faster. However on Running `flutter test` or very_good test --no-optimization  all tests pass but on running `very_good test` some tests fail. Would you know why?
Attaching screenshots
Flutter test or very_good test --no-optimization:
<img width="430" alt="Screen Shot 2022-09-15 at 10 01 30 AM" src="https://user-images.githubusercontent.com/43588269/190425531-1d93cbcd-1774-4be1-add5-e56bce1ea605.png">

Very_good test:
<img width="555" alt="Screen Shot 2022-09-15 at 10 08 14 AM" src="https://user-images.githubusercontent.com/43588269/190425659-27a8f4a6-4602-4083-9fe6-e17aca9d184a.png">

**Comment by felangel** [comment]
Hi @ShivamMattoo33 👋 
Thanks for opening an issue!

This is pretty common if you have side-effects within your tests that will affect other tests. I highly recommend running on smaller and smaller subsets of tests to narrow down which tests are causing the problem. You'll likely notice that the tests are altering some external state which is causing other tests to fail. Hope that helps 👍

**Comment by ShivamMattoo33** [comment]
Thank you I can do that
