### ISSUE TITLE
Regarding Tests again

### ISSUE THREAD

**Issue by ShivamMattoo33** [VeryGoodOpenSource/very_good_cli#498]
Hey @felangel  Sorry to bother you again

So the Tests fail when I run the command very_good test and you recommended going with smaller pieces at a time and figuring out whats wrong

I tried going individual directories but tests pass when i do very_good test **any directory or path** 

Basically the only time tests fail is when I run  very_good test which makes it impossible to figure out what all tests are failing and whats the reason

Any suggestions

**Comment by felangel** [comment]
You can start with one test and slowly add one test at a time until you encounter a failure.

**Comment by ShivamMattoo33** [comment]
lol I have 2000 tests. Isnt there a better way

**Comment by felangel** [comment]
> lol I have 2000 tests. Isnt there a better way

You can try to spot the issue by looking for any variables that are references across multiple tests or any global, singletons that are used throughout your tests. You can also debug the failing test to try to understand why it's failing and that should give you some hints.

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps for very_good_cli 👍
