### ISSUE TITLE
fix: animation in intellij idea (android studio) IDE

### ISSUE THREAD

**Issue by yehorh** [VeryGoodOpenSource/very_good_cli#499]
**Description**
The `very_good packages get` command in the built-in terminal produces stdout unexpected progress artifacts. 

**Steps To Reproduce**

1. Go to 'open flutter project in any supported 'jetbrains ide'
2. Open build in terminal emulator (⌘ + f12)
3. Type `very_good packages get`

**Screenshots**

https://user-images.githubusercontent.com/10909216/190867504-70da6d39-70c6-4685-873d-6f11a381ab25.mov

**Comment by tyypgzl** [comment]
This error also happens when creating files with mason.
