### ISSUE TITLE
docs: project creation commands on pub.dev need updating

### ISSUE THREAD

**Issue by danallen88** [VeryGoodOpenSource/very_good_cli#503]
**Description**
The documentation on the [pub.dev page](https://pub.dev/packages/very_good_cli) appears to be out of sync with the [GitHub README](https://github.com/VeryGoodOpenSource/very_good_cli#very_good-create) in the section about how to create a new package.  Specifically, the section on usage on the pub.dev site has:

```bash
Usage: very_good create <output directory>
-h, --help                    Print this usage information.
    --project-name            The project name for this new project. This must be a valid dart package name.
```

Whereas the README has:

```bash
Usage: very_good create <project name>
-h, --help                    Print this usage information.
-o, --output-directory        The desired output directory when creating a new project.
```

It appears the section in README follows the correct behavior of the CLI.  I'd offer a PR but I'm not sure how these changes manage to get published to the pub.dev site.  Thanks for looking!

**Comment by felangel** [comment]
Hi @danallen88 👋 
Thanks for opening an issue!

We just haven't published a new version of `very_good_cli` yet because we're planning to lump in some other updates shortly. This should be resolved in the next few days -- sorry for the inconvenience!

**Comment by danallen88** [comment]
My mistake, thank you for clarifying @felangel! I'll close this issue with that understanding.
