### ISSUE TITLE
feat: How to internationalize the name of the application in the iOS project generated by very good cli?

### ISSUE THREAD

**Issue by kimmy214** [VeryGoodOpenSource/very_good_cli#510]
How to internationalize the name of the application in the iOS project generated by `very good cli`? Internationalization using `InfoPlist.strings` results in the same application name under different flavors.

**Comment by renancaraujo** [comment]
Hello @kimmy214 

Just went step by step on this [tutorial](https://medium.com/@g123k/translate-info-plist-file-ios-macos-in-flutter-ea14be4427f9) and after setting the `InfoPlist.string`s file with the following content, I could make it work.


```
/// InfoPlist.strings (en)
"CFBundleDisplayName" = "The app";


/// InfoPlist.strings (es)
"CFBundleDisplayName" = "El app";
```

**Comment by renancaraujo** [comment]
W

**Comment by kimmy214** [comment]
@renancaraujo This modification will cause a problem, that is, the application names of different flavors are the same.

**Comment by renancaraujo** [comment]
Yeah, I spent soem hours trying some different approaches but seems that there is no pretty way to localize build settings (the original bundle display name is a user defined build setting). 

I found this [answer](https://stackoverflow.com/a/67231243) and it seems to work even though it is pretty tricky and hacky, but apparently that is the code way of doing things.

**Comment by kimmy214** [comment]
I also found this answer, thanks.

**Comment by renancaraujo** [comment]
Another option could be creating new targets for flavors but that would break the flutter tooling.
