### ISSUE TITLE
fix: --org-name at least 2 parts. Why ?

### ISSUE THREAD

**Issue by rubensdemelo** [VeryGoodOpenSource/very_good_cli#557]
**Description**
Using the --org-name flag needs 2 parts.  

`very_good create super --org-name=app` is a invalid command.

`very_good create super --org-name=app.super` is a valid command and the package name is `app.super.super`

The `very_good_cli` concatenate org and project name.  

Why only 1 part on --org-name flag is **not** allowed ? 

https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/commands/create/create.dart#L32

**Comment by renancaraujo** [comment]
You can use `--application-id`for the single part option. See #280 for more context
