### ISSUE TITLE
fix: very_good test fails when some tests have a space in their golden name

### ISSUE THREAD

**Issue by Cteq3132** [VeryGoodOpenSource/very_good_cli#565]
**Description**
When running `very_good test` in a flutter repository which have golden tests, the commands fails to find the correct golden.

**Steps To Reproduce**

1. Create a sample app with `very_good create example`
2. Replace the `renders CounterView` test in `test/counter/view/counter_page_test.dart` by: 
```dart
testWidgets('renders CounterView', (tester) async {
  await tester.pumpApp(const CounterPage());
  expect(find.byType(CounterView), findsOneWidget);

  await expectLater(
    find.byType(CounterView),
    matchesGoldenFile('counter page.png'),
  );
});
```
4. Generate golden with `flutter test --update-goldens`
5. Run `very_good test` and see this error:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═══════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      ListMixin.singleWhere (dart:collection/list.dart:202:5)
#1      _TestOptimizationAwareGoldenFileComparator.getTestUri (file:///[path-to-the-project]/test/.test_runner.dart:46:10)
#2      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:50:50)
#3      _expect (package:test_api/src/expect/expect.dart:98:26)
#4      expectLater (package:test_api/src/expect/expect.dart:62:5)
#5      expectLater (package:flutter_test/src/widget_tester.dart:497:23)
#6      main.<anonymous closure>.<anonymous closure> (file:///[path-to-the-project]/test/counter/view/counter_page_test.dart:25:13)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  renders CounterView
```

**Expected Behavior**
The expected behavior is for the command `very_good test` to succeed.

**Additional Context**
When debugging, I found the `getTestUri` helper in the `_TestOptimizationAwareGoldenFileComparator` class:
```dart
Uri getTestUri(Uri key, int? version) {
  final keyString = key.path;
  return Uri.parse(goldenFilePaths.singleWhere((goldenFilePath) => goldenFilePath.endsWith(keyString)));
}
```

By adding a breakpoint in this function, I found that the `keystring` was `counter%20page.png` whereas the `goldenFilePaths` list in which are all the golden paths contains the following element: `[path-to-the-project]/test/counter/view/counter page.png`.

So in one case we have a %20 and in the other a space, which leads the `Uri.parse(goldenFilePaths.singleWhere((goldenFilePath) => goldenFilePath.endsWith(keyString)))` line to throw an error as no element is found.

I don't know if the approach for a fix would be to store all the golden paths with a %20 instead of spaces or to replace all the %20 in the `keystring` of the `getTestUri` method?

Thank you for your time!

**Comment by renancaraujo** [comment]
@Kirpal can you comment on this so we can assign you?

**Comment by Kirpal** [comment]
Yeah, it's PR #651
