### ISSUE TITLE
fix: very_good test Invalid argument(s): Groups may not be async.

### ISSUE THREAD

**Issue by dipakp2726** [VeryGoodOpenSource/very_good_cli#570]
**Description**
when run very_good test gives following error

✓ Optimizing tests (2.1s)
Failed to load "/Users/dipak/Desktop/projects/alliwant/test/.test_runner.dart": Invalid argument(s): Groups may not be async.
package:test_api                                  Declarer.group
package:flutter_test/src/test_compat.dart 189:13  group
test/.test_runner.dart 30:3                       main

loading /Users/dipak/Desktop/projects/alliwant/test/.test_runner.dart /Users/dipak/Desktop/projects/alliwant/test/.test_runner.dart (FAILED)
00:13 -1: Some tests failed.
Failing Tests:
 - [ERROR] test/.test_runner.dart:30:3

**Steps To Reproduce**
run very_good test

**Expected Behavior**
should run tests

**Screenshots**
![Screenshot 2022-11-15 at 9 06 20 PM](https://user-images.githubusercontent.com/36990991/201960769-352d49e7-2c3d-457e-bf5d-7a461c9ff771.png)

**Additional Context**
flutter test run successfully

**Comment by agacemi** [comment]
@dipakp2726  Could you run `very_good test`  and interrupt it with ctrl-c before finishing (because at finishing, .test_runner is deleted). Then look at .test_runner.dart to have more info about reason of the failure.

**Comment by dipakp2726** [comment]
content of .test_runner.dart 
<details><summary>Click To Expand</summary>


```

// GENERATED CODE - DO NOT MODIFY BY HAND
// Consider adding this file to your .gitignore.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';


import 'order/order_listing_test.dart' as order_order_listing_test_dart;
import 'order/order_test.dart' as order_order_test_dart;
import 'offer/offer_listing_test.dart' as offer_offer_listing_test_dart;
import 'offer/offer_test.dart' as offer_offer_test_dart;
import 'user/user_test.dart' as user_user_test_dart;
import 'user/user_auth_test.dart' as user_user_auth_test_dart;
import 'payment_method/bank_info_test.dart' as payment_method_bank_info_test_dart;
import 'payment_method/payment_method_test.dart' as payment_method_payment_method_test_dart;
import 'item/post_image_test.dart' as item_post_image_test_dart;
import 'item/post_item_test.dart' as item_post_item_test_dart;
import 'address/address_test.dart' as address_address_test_dart;
import 'wallet/wallet_test.dart' as wallet_wallet_test_dart;
import 'cart/cart_test.dart' as cart_cart_test_dart;
import 'ensure_build_test.dart' as ensure_build_test_dart;

void main() {
  goldenFileComparator = _TestOptimizationAwareGoldenFileComparator();
  group('order_order_listing_test_dart', order_order_listing_test_dart.main);
  group('order_order_test_dart', order_order_test_dart.main);
  group('offer_offer_listing_test_dart', offer_offer_listing_test_dart.main);
  group('offer_offer_test_dart', offer_offer_test_dart.main);
  group('user_user_test_dart', user_user_test_dart.main);
  group('user_user_auth_test_dart', user_user_auth_test_dart.main);
  group('payment_method_bank_info_test_dart', payment_method_bank_info_test_dart.main);
  group('payment_method_payment_method_test_dart', payment_method_payment_method_test_dart.main);
  group('item_post_image_test_dart', item_post_image_test_dart.main);
  group('item_post_item_test_dart', item_post_item_test_dart.main);
  group('address_address_test_dart', address_address_test_dart.main);
  group('wallet_wallet_test_dart', wallet_wallet_test_dart.main);
  group('cart_cart_test_dart', cart_cart_test_dart.main);
  group('ensure_build_test_dart', ensure_build_test_dart.main);
}


class _TestOptimizationAwareGoldenFileComparator extends LocalFileComparator {
  final List<String> goldenFilePaths;

  _TestOptimizationAwareGoldenFileComparator()
      : goldenFilePaths = _goldenFilePaths,
        super(_testFile);

  static Uri get _testFile {
    final basedir =
        (goldenFileComparator as LocalFileComparator).basedir.toString();
    return Uri.parse("$basedir/.test_runner.dart");
  }

  static List<String> get _goldenFilePaths =>
      Directory.fromUri((goldenFileComparator as LocalFileComparator).basedir)
          .listSync(recursive: true, followLinks: true)
          .whereType<File>()
          .map((file) => file.path)
          .where((path) => path.endsWith('.png'))
          .toList();

  @override
  Uri getTestUri(Uri key, int? version) {
    final keyString = key.path;
    return Uri.parse(goldenFilePaths
        .singleWhere((goldenFilePath) => goldenFilePath.endsWith(keyString)));
  }
}


```

</details>

**Comment by agacemi** [comment]
Please, could you, by elimination, identify the test causing the test failure to provide a reproducible sample. Maybe `user/user_test.dart`that causes the test failure ..

**Comment by dipakp2726** [comment]
i tried removing user/user_test.dart then it gave same error on another group I removed it also,then again it goes happening,

in the end I left  with empty tests

**Comment by dipakp2726** [comment]
all the tests are mock API tests ,

```
Future<void> main() async {
  late MockUserRepo repo;

  late UserProvider provider;

  final hiveStorageService = StorageService.instance;
  final valueHolder = MockValueHolder();

  setUpAll(() async {
    await setUpTestHive();
    await hiveStorageService.init();
    repo = MockUserRepo();
    GetIt.I.registerSingleton(ValueProvider.instance);
    provider = UserProvider(repo: repo, valueHolder: valueHolder);
  });

  tearDownAll(() async {
    await hiveStorageService.close();
  });

  /// User Profile Update
  group('User Profile Update', () {
    final param = <String, dynamic>{};
    test('Should User Profile Update', () async {
      // Arrange
      final model = Resource<User>.completed(
        User(userName: '', userPhone: '', userEmail: ''),
      );

      when(() => repo.postProfileUpdate(param)).thenAnswer((_) async => model);

      // Act
      final resource = await provider.postProfileUpdate(param);

      // Assert
      expect(resource, isA<Resource<User>>());
      expect(resource.hasSuccess, true);
      expect(resource.data, model.data);
    });

    test('Should Error In User Profile Update', () async {
      // Arrange
      const error = 'Error In User Profile Update';

      final model = Resource<User>.error(error);

      when(() => repo.postProfileUpdate(param)).thenAnswer((_) async => model);

      // Act
      final resource = await provider.postProfileUpdate(param);

      // Assert
      expect(resource, isA<Resource<User>>());
      expect(resource.hasError, true);
      expect(resource.message, error);
    });
  });

}
```

**Comment by NonymousMorlock** [comment]
ugh, I've been trying to fix this for days now, but ended up deleting one test after another, nothing is working, and it also causes my git workflow to have the same errors, didn't even know it was a bug

**Comment by NonymousMorlock** [comment]
I found a solution, so, I followed what @agacemi  said, about cutting the test off then I ctrl+clicked all the test.main to get me to all the tests, and I found one of my test's void main was async, 

```
void main() async {
    // do some async stuff
}
```

and the group in the test_runner was calling that async main method as the body of the group, and that was causing the error
so, I removed the async and put the async call in it's own asynchronous method and then called it in my setUp

So, if you have any async main methods in your test, remove it, that's the cause of the error

**Comment by dipakp2726** [comment]
> I found a solution, so, I followed what @agacemi said, about cutting the test off then I ctrl+clicked each of the test.main to get me to all the tests, and I found one of my test's void main was async,
> 
> ```
> void main() async {
>     // do some async stuff
> }
> ```
> 
> and the group in the test_runner was calling that async main method as the body of the group, and that was causing the error so, I removed the async and put the async call in its own asynchronous method and then called it in my setUp
> 
> So, if you have any async main methods in your test, remove it, that's the cause of the error

this does resolve it.

**Comment by dipakp2726** [comment]
It would be good if this can be added in the documentation that while using these tests with optimization main method can't be async

**Comment by agacemi** [comment]
@dipakp2726 @NonymousMorlock Good work. It would great to open a new pull request to improve documentation with troubleshooting section including this case.
