### ISSUE TITLE
Update Blog Posts and Documentation

### ISSUE THREAD

**Issue by BeatriceMitchell** [VeryGoodOpenSource/very_good_cli#581]
Existing blog posts will need to be updated to reflect any changes to the 'create' command.

- [ ] readme
- [ ] vgv.dev
- [ ] all blog posts
- [ ] reminiscent usage help messages/dartdoc entries

**Comment by renancaraujo** [comment]
Related https://github.com/VeryGoodOpenSource/very_good_cli/issues/490
