### ISSUE TITLE
Not optimized code in cli.dart

### ISSUE THREAD

**Issue by crifurch** [VeryGoodOpenSource/very_good_cli#604]
https://github.com/VeryGoodOpenSource/very_good_cli/blob/fcd5750cbd18b891ed3436ce02169318d92b10a3/lib/src/cli/cli.dart#L143

Test on 285675 files

```
bool _isPubspec(FileSystemEntity entity) {
  final segments = p.split(entity.path).toSet();
  if (segments.intersection(_ignoredDirectories).isNotEmpty) return false;
  if (entity is! File) return false;
  return p.basename(entity.path) == 'pubspec.yaml';
}
```

Performance result: 1414 milliseconds

//change check order
```
bool _isPubspec(FileSystemEntity entity) {
  if (entity is! File) return false;
  if(p.basename(entity.path) != 'pubspec.yaml') return false;
  final segments = p.split(entity.path).toSet();
  return segments.intersection(_ignoredDirectories).isEmpty;
}
```

Performance result: 559 milliseconds

// solution 1
```
RegExp _pathSeparatorRegex = RegExp(r'[\\/]');
bool _isPubspec(FileSystemEntity entity) =>
    entity is File &&
    entity.path.endsWith('pubspec.yaml')&&
    !entity.path.split(_pathSeparatorRegex).any(_ignoredDirectories.contains);
```

Performance result: 24 milliseconds

// solution 2
```
RegExp _pathSeparatorRegex = RegExp(r'[\\/]');
bool _isPubspec(FileSystemEntity entity) =>
    entity is File &&
    (entity.path.endsWith('pubspec.yaml') ||
        entity.path.endsWith('pubspec.yml')) &&
    !entity.path.split(_pathSeparatorRegex).any(_ignoredDirectories.contains);
```

Performance result: 27 milliseconds

//solution 3
```
RegExp _pathSeparatorRegex = RegExp(r'[\\/]');
RegExp _pubspecRegex = RegExp(r'pubspec\.ya?ml$');
bool _isPubspec(FileSystemEntity entity) =>
    entity is File &&
        entity.path.contains(_pubspecRegex)&&
        !entity.path.split(_pathSeparatorRegex).any(_ignoredDirectories.contains);
```

Performance result: 102 milliseconds

I think it's better to use solution 1 or solution 2, the execution result will be the same.

**Comment by tomarra** [comment]
Hi @crifurch 👋 thanks for the suggestion here. We haven't gotten any complaints about performance being a limiting factor in use of the tool so not seeing a huge need to implement a fix at this time. If you do feel like this is worth contributing back into the repo though please feel free to make the change and open up a pull request. The team would be more then happy to work through the review and landing process with you.

Closing out as "won't fix" as this won't get priority in our current backlog.
