### ISSUE TITLE
fix: --org-name flag is not allowed ?

### ISSUE THREAD

**Issue by Wadie-ess** [VeryGoodOpenSource/very_good_cli#613]
**Description**
Using the --org-name flag needs 2 parts.

very_good create super --org-name=app is a invalid command.

very_good create super --org-name=app.super is a valid command and the package name is app.super.super

The very_good_cli concatenate org and project name.

Why only 1 part on --org-name flag is not allowed ?

**Comment by felangel** [comment]
Hi @Wadie-ess 👋 
Thanks for opening an issue!

This is because org name is used to generate the `applicationId` which must contain at least two segments based on the Android docs:

> It must have at least two segments (one or more dots).

https://developer.android.com/studio/build/configure-app-module

Hope that helps 👍

**Comment by tomarra** [comment]
Looks like this was answered with no feedback so far. @Wadie-ess if you are still having an issue with this please open a new ticket with more details. Closing as "won't fix" as there is no action being taken here.
