### ISSUE TITLE
feat: support Flutter test's --platform flag

### ISSUE THREAD

**Issue by mtwichel** [VeryGoodOpenSource/very_good_cli#620]
**Description**
I have a project that uses the `dart:html` package in one of it's dependencies (it only runs on Flutter web). If I run the `very_good test` command, I get errors like this:

```stacktrace
Error: Not found: 'dart:html'
import 'dart:html';
```
I am able to run the tests using `flutter test --platform chrome`. However, it looks like Very Good CLI currently doesn't support the `--platform` flag.

**Comment by felangel** [comment]
Hey @mtwichel 👋
Thanks for reporting the, will take a closer look asap. We don’t support the platform flag in the very_good test command because it is not officially supported by the flutter_tools: https://github.com/flutter/flutter/blob/51c2af56c9f4b5728c771d229baa19a286c01aa0/packages/flutter_tools/lib/src/commands/test.dart#L160

**Comment by mtwichel** [comment]
> We don’t support the platform flag in the very_good test command because it is not officially supported by the flutter_tools

That makes a lot of sense, thanks for the reply.

per that comment you linked to
> and may be removed entirely in the future.

It sounds like maybe I should set up the dynamic import so that it doesn't fail on the Dart VM 😅 I don't know why that didn't occur to me last night haha

**Comment by mtwichel** [comment]
Hey just an FYI for anyone who stumbles on this, I solved my issue using code like this:

```dart
export 'src/my_actual_code_that_uses_html'
  if (dart.library.io) 'src/dummy_code_that_wont_be_used';
```

I'm not really able to unit test the real code that uses `dart:html`, but it doesn't seem like that's well supported by Flutter atm (see [this comment](https://github.com/flutter/flutter/blob/51c2af56c9f4b5728c771d229baa19a286c01aa0/packages/flutter_tools/lib/src/commands/test.dart#L160))

@felangel, feel free to close if you think that's appropriate :)

**Comment by felangel** [comment]
> Hey just an FYI for anyone who stumbles on this, I solved my issue using code like this:
> 
> ```dart
> export 'src/my_actual_code_that_uses_html'
>   if (dart.library.io) 'src/dummy_code_that_wont_be_used';
> ```
> 
> I'm not really able to unit test the real code that uses `dart:html`, but it doesn't seem like that's well supported by Flutter atm (see [this comment](https://github.com/flutter/flutter/blob/51c2af56c9f4b5728c771d229baa19a286c01aa0/packages/flutter_tools/lib/src/commands/test.dart#L160))
> 
> @felangel, feel free to close if you think that's appropriate :)

Thanks for the update @mtwichel. You should be able to use plain dart test which supports the chrome platform 👍

Closing for now but happy to continue the discussion if you have additional thoughts/questions.
