### ISSUE TITLE
error when create flutter_app

### ISSUE THREAD

**Issue by hwangblood** [VeryGoodOpenSource/very_good_cli#633]
```
$ very_good create flutter_app my_app --desc "My new Flutter app"  

✓ Generated 239 file(s) (3.3s)
✓ Running "flutter packages get" in ./my_app (0.4s)
Unhandled exception:
ProcessException: Standard error
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Generating synthetic localizations package failed with 1 error:

Exception: Found syntax errors.
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:125:7)
#1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:96:7)
<asynchronous suspension>
#2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:98:11)
<asynchronous suspension>
#3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:284:13)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:84:5)
<asynchronous suspension>
#5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:28:5)
<asynchronous suspension>
#6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:20:5)
<asynchronous suspension>
#7      CreateSubCommand.runCreate (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:226:5)
<asynchronous suspension>
#8      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:200:20)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#11     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#12     main (file:///home/blood/.pub-cache/hosted/pub.flutter-io.cn/very_good_cli-0.10.0/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Comment by muhammadshahidraficp** [comment]
very_good cli project creation stuck at Generated 239 file(s) (1.4s)

**Comment by renancaraujo** [comment]
Hello @hwangblood, can you try running `flutter packages get` in the created apps repository?

Also, the output of `flutter doctor` and the version of very_good_cli which you are using could be helpful to find out what is happening?

**Comment by hwangblood** [comment]
very_good command  get stuck only on Flutter 3.7 and very_good_cli 0.10.0, but when i downgrade flutter 3.3.10 very_good_cli works well

**Comment by renancaraujo** [comment]
Your original error output suggests an error within `flutter packages get` execution. 
After getting facing that error, can you try running` flutter packages get` in the created apps repository?

**Comment by hwangblood** [comment]
> Your original error output suggests an error within `flutter packages get` execution. After getting facing that error, can you try running` flutter packages get` in the created apps repository?

I have tried, error still happen `Generating synthetic localizations package failed with 1 error:`

**Comment by hwangblood** [comment]
> Your original error output suggests an error within `flutter packages get` execution. After getting facing that error, can you try running` flutter packages get` in the created apps repository?

and the error is not happend in very_good_cli leastest and flutter 3.3.10

**Comment by renancaraujo** [comment]
If that runs on flutter packages get, it seems like there is an error on your version fo the flutter tools.

**Comment by hwangblood** [comment]
> If that runs on flutter packages get, it seems like there is an error on your version fo the flutter tools. 

yes
