### ISSUE TITLE
Can't create macOS 

### ISSUE THREAD

**Issue by mstfkhazaal** [VeryGoodOpenSource/very_good_cli#683]
When running create command, I get all flutter platforms crated except macOS. I have tried adding the platforms and --macOS=true command with no avail.

**Comment by rasmus-dybmose** [comment]
Read the first line
https://cli.vgv.dev/docs/templates/core#app-features-

I don't know how well this works but you can try this command out in the application folder
`flutter create --platforms=macos .`

**Comment by mstfkhazaal** [comment]
@rasmus-dybmose  thanks
