### ISSUE TITLE
Remove Very Good Cli Splash Screen

### ISSUE THREAD

**Issue by osamamohammed98** [VeryGoodOpenSource/very_good_cli#688]
how to remove gray very good cli Splash Screen

**Comment by renancaraujo** [comment]
Hello there,

You have to be a little more specific about what this refers to. Is this on a template created with the create command? On a specific platform?

**Comment by osamamohammed98** [comment]
I have used very good cli
To create my project after I created it
A gray splash screen appears with a logo on it
I removed the logo, but I could not remove the gray color
I used the native splash library, and now I have 2 splash screens, and the The problem got bigger

**Comment by osamamohammed98** [comment]
https://user-images.githubusercontent.com/27555246/226846882-665822cf-831c-423e-abea-c77260357690.mov

You can look here
A gray screen appears
Then the original screen of the application appears in white
Then it goes to flutter

**Comment by renancaraujo** [comment]
Can you check if that happens on release mode?

**Comment by osamamohammed98** [comment]
the release need to do signing configuration 
i try stop it but the APK Not Installed

**Comment by alestiago** [comment]
Thanks @osamamohammed98 for opening the issue 💙 !

I would love to get this to reproduce in my personal computer (locally). Do you mind specifying the steps I need to do to get this issue showing up?

It would also help us if you include the output of your `flutter doctor -v`, the output of `very_good --veresion` and the android version you're device is on.

**Comment by osamamohammed98** [comment]
I just executed the command to create a Flutter application
Then I removed the image that appears in the splash screen
Then I tried to remove the gray color that appeared, but I couldn't
Note that a gray screen appears because the theme of my phone is dark
Then I added the Splash Native creation library, so it appeared to me
A gray screen, then the original screen of the Android application, then it moves to flutter framework

**Comment by osamamohammed98** [comment]
% flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-PS)
    • Flutter version 3.7.3 on channel stable at /Users/osama/flutter_sdk/flutter_37
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (6 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/osama/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/osama/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Redmi Note 8 (mobile) • 115a432b • android-arm64  • Android 11 (API 30)
    • macOS (desktop)       • macos    • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by osamamohammed98** [comment]
very_good --version 
0.12.2

**Comment by iamnabink** [comment]
Facing a similar issue, also flavours icon [from flutter_launcher_icons] not working , any fixes yet?

**Comment by renancaraujo** [comment]
linking #481

**Comment by osamamohammed98** [comment]
> linking #481

I try it and it's not successful
I'm solving it by create flutter project without very good
And add flavor manual
And make all features manual 
And it's working now

**Comment by xbdh** [comment]
1. just  close xcode ，
2. close ios simulator ，
3. flutter clean， 
4. rm -rf ios/build        rm -rf ios/Pods  rm -rf ios/.symlinks ，
5. flutter pub  get ，
6. cd ios                                                    
pod deintegrate
pod setup
pod install
cd ..   
then 
use flutter_native_splash to generate new spalsh page
remember everytime you generate new spalshpage,  repeat 1-6 above 

fuck xcode

**Comment by lingme** [comment]
> 1. just  close xcode ，
> 2. close ios simulator ，
> 3. flutter clean，
> 4. rm -rf ios/build        rm -rf ios/Pods  rm -rf ios/.symlinks ，
> 5. flutter pub  get ，
> 6. cd ios
>    pod deintegrate
>    pod setup
>    pod install
>    cd ..
>    then
>    use flutter_native_splash to generate new spalsh page
>    remember everytime you generate new spalshpage,  repeat 1-6 above
> 
> fuck xcode

oh my god, this is working !!!!  thanks very much
