### ISSUE TITLE
fix: Missing  l10n documentation in the flutter project's readme.md 

### ISSUE THREAD

**Issue by tanmoy27112000** [VeryGoodOpenSource/very_good_cli#691]
**Description**
The command to generate the class when new strings are added to the arb file is missing

**Steps To Reproduce**

1. Create a flutter project using the cli
2. Check the readme.md file

**Expected Behavior**
The documentation should contain the command that has to be used to generate the classes for locale.

i.e
use the following command to generate the new string
```
flutter gen-l10n
```

**Comment by alestiago** [comment]
Thanks for opening this issue @tanmoy27112000 !

I think this issue should be opened in the Very Good Core repository. Where the template that gets generated using `very_good create` actually is. Let me know if this makes sense :D!

The l10n also gets generated automatically when running a `flutter run`. However, it doesn't hurt documenting this in the `README.md`.

**Comment by alestiago** [comment]
Closing in favour of https://github.com/VeryGoodOpenSource/very_good_core/issues/259.
