### ISSUE TITLE
fix: every Android flavor has the same label

### ISSUE THREAD

**Issue by MarkOSullivan94** [VeryGoodOpenSource/very_good_cli#724]
**Description**

Whenever running each of the app flavors it is using the name which is entered when generating the app template instead of the name specified in the build.gradle file.

E.g. The name I used for my app is `very_good_app` and so this is the name shown below the icon when viewing all apps on my device.

This becomes a problem whenever you use the same icon for all x3 flavors.

**Steps To Reproduce**

1. `very_good create flutter_app very_good_app --desc "An example app build with very_good_cli" --org "com.example"`
2. Run development flavor of the Android app
3. Run staging flavor of the Android app
4. You will see both have the same name

**Expected Behavior**
They should have the names which are specified in the build.gradle file as shown below

```
manifestPlaceholders = [appName: "Very Good App"]

manifestPlaceholders = [appName: "[STG] Very Good App"]

manifestPlaceholders = [appName: "[DEV] Very Good App"]
```

So instead of showing `very_good_app` for all 3 flavors, I should see "[STG] Very Good App" when searching for the staging version of the app.

**Screenshots**

![Screenshot_1681691590](https://user-images.githubusercontent.com/6950843/232353054-9f84fb27-f3ac-476a-b422-91e1f12cdf54.png)

**Additional Context**

This is an easy quick fix, instead of the label being the name of the app when creating the template it should be `appName` instead.

What is shown right now for the label: `android:label="very_good_app"`

Needs to be changed to: `android:label="${appName}"` 

The name used in the gradle file is a bit misleading, as you can see it's the label of the app and so should use a variable named as such

**Comment by alestiago** [comment]
I've been unable to reproduce using a Mi A2 running Android 10.

I did:
1. `very_good create flutter_app very_good_app --desc "An example app build with very_good_cli" --org "com.example"`
2.`flutter run --flavor staging -t lib/main_staging.dart`
3. `flutter run --flavor development -t lib/main_development.dart`

![CleanShot 2023-05-04 at 19 14 42@2x](https://user-images.githubusercontent.com/44524995/236292831-36d7a1ef-4afe-4ca6-8a21-6679d7471717.png)


@MarkOSullivan94 can when running those same commands do you still get different application? If so, can you share the output of `flutter doctor -v`?

**Comment by MarkOSullivan94** [comment]
@alestiago your screenshot has shown that you are experiencing the exact same issue 😄 

The names of **both** flavors of the apps are `very_good_app` and not `[DEV] Very Good App` for the dev flavor and `[STG] Very Good App` for the staging flavor

**Comment by alestiago** [comment]
@MarkOSullivan94 sorry, you're right. I'll look into updating their labels.

From the screenshot you have in the descriptions it seems that you get a single app instead of two, contrary to what I am getting. Was this after running both the dev and staging?
