### ISSUE TITLE
fix: Cannot upgrade intl to ^0.18.1

### ISSUE THREAD

**Issue by aalex** [VeryGoodOpenSource/very_good_cli#746]
**Description**
`very_good create flutter_app` creates a pubspec.yaml file that points to an old version of the `intl` package. When we upgrade the version of intl, it displays an error message when running `flutter pub get`: 

**Steps To Reproduce**

1. Run `very_good create flutter_app`
2. Upgrade the version of `intl` from `^0.18.0` to `^0.18.1`
3. Run `flutter pub get`
4. It displays an error message:

```
Because project_name depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because project_name depends on intl ^0.18.1, version solving failed.
```

**Expected Behavior**
It should simply install the new dependencies without complaining.

**Additional Context**
If we remove `intl`, it might fix it, but I haven't verified if the i18n still works.

**Comment by renancaraujo** [comment]
Hello there. As of today, the stable channel of Flutter depends on intl 0.18.0. You cannot use a version of intl that is not support by the version of flutter you are using. If you need intl 0.18.1, you should switch to master or maybe the beta channel of Flutter.
