### ISSUE TITLE
fix: Different coverage rates locally and in Github Actions

### ISSUE THREAD

**Issue by mmarchal** [VeryGoodOpenSource/very_good_cli#748]
**Description**
When I run this command `very_good test --coverage --exclude-coverage "{**/*.g.dart,**/*.freezed.dart,**/entities/**,**/*_state.dart,**/core/**}"  --min-coverage 80.0` in local environment, I have a success but with the Github Actions CICD and the same command, I have a fail job.
The number of different tests executing is the same : 64

**Screenshots**
Local : 
![image](https://github.com/VeryGoodOpenSource/very_good_cli/assets/25179165/8d132e33-c921-4914-9de3-0f71be1c8e66)

CICD Github Action : 
![image](https://github.com/VeryGoodOpenSource/very_good_cli/assets/25179165/229635fb-4832-4f26-ba2b-7ad4ffa1078e)

Additional Context : 

![image](https://github.com/VeryGoodOpenSource/very_good_cli/assets/25179165/50bc0f0d-4ae0-4dee-8dff-b17f7e979ba0)

**Comment by renancaraujo** [comment]
Hello there, 

Could you provide a minimal sample repository/code to reproduce the bug? Knowing how the workflow is set up is key to discovering what happens.
