### ISSUE TITLE
bug: can't run with FVM and Flutter 3.10.0

### ISSUE THREAD

**Issue by gugadev** [VeryGoodOpenSource/very_good_cli#749]
**Description**
Just upgraded from 0.14.0 to 0.15.0 and it just got broke.

**Steps To Reproduce**

1. Set Flutter 3.10.0 as global version through FVM:

```
fvm global 3.10.0
```

2. Install or upgrade very_good_cli:

```
very_good update
```

or

```
fvm dart pub global activate very_good_cli
```
3. Try to use very-good:

```bash
very_good create flutter_app my_app`
```
4. See error below:

```
Can't load Kernel binary: Invalid kernel binary format version.
very_good_cli 0.15.0 doesn't support Dart 2.19.3.
```

Which is strange because I only have Flutter 3.10.0 installed which comes with dart `3.0.0` and the error tells me that very_good is using `2.19.3`.

**Comment by intsitesdotru** [comment]
@gugadev I had a similar problem
try to run flutter doctor, it showed the problem with path to dart
found the solution [here](https://stackoverflow.com/questions/75343825/how-to-fix-this-flutter-doctor-warning-dart-on-your-path-resolves-to-macos)

**Comment by gugadev** [comment]
Hi @intsitesdotru , thanks for your feedback. Yep, the issue was an old standard installation (global) of Flutter 2.x. After removing dart with homebrew, everything goes fine now.

Gonna close the issue. Thank you!
