### ISSUE TITLE
fix: Cannot Update very_good_cli

### ISSUE THREAD

**Issue by workerbee22** [VeryGoodOpenSource/very_good_cli#752]
**Description**
Currently installed version. Installed via:

```
dart pub global activate very_good_cli
```
Current installed version is `very_good_cli 0.14.0`

**Steps To Reproduce - Update**

1. Attempted to update with:

```very_good update```

Result is:

```
✓ Checked for updates (0.5s)
✗ Updating to 0.15.0 (0.8s)
Error updating Very Good CLI: The current Dart SDK version is 2.19.5.

Because pub global activate depends on very_good_cli >=0.15.0 which requires SDK version >=3.0.0 <4.0.0, version solving failed.
```

**Expected Behavior**
Does not fail to update.

**Comment by alestiago** [comment]
I believe this might be due to your Flutter version not using Dart 3.

Try:
1. Upgrade Flutter (via command line `flutter upgrade`)
2. Upgrade your project to Dart 3 (by updating the `pubspec.yaml` SDK versioning and dependencies)

Let me know if this resolves this issue. If it does not, please share the output of `flutter doctor`.

**Comment by workerbee22** [comment]
Nope. Flutter is already Dart 3:

```
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (4 days ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

**Comment by workerbee22** [comment]
Resolved! 

Somehow I had installed Dart v2.19.5 from `brew` as well as from the Flutter install. So I had two versions installed.

Resolved by removing the brew Dart install with `brew remove dart`.

After that `very_good update` worked correctly and updated the package.
