### ISSUE TITLE
fix: package name not visible in output when run tests recursive

### ISSUE THREAD

**Issue by DFelten** [VeryGoodOpenSource/very_good_cli#754]
**Description**

When running all tests recursive the package title is not visible in the output. 

`very_good test --optimization --coverage -r`

Folder structure:

```
packages/name123
packages/name456
packages/name789
```

Output:

```
✓ Optimizing tests (56ms)
00:16 +58: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages...
✓ Optimizing tests (61ms)
00:20 +377: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages...
✓ Optimizing tests (54ms)
00:14 +31: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages...
✓ Optimizing tests (57ms)
```

**Expected Behavior**

Title of each package is visible in the output:

```
✓ Optimizing tests (56ms)
00:16 +58: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages/name123...
✓ Optimizing tests (61ms)
00:20 +377: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages/name456...
✓ Optimizing tests (54ms)
00:14 +31: All tests passed!
Running "flutter test" in /Users/danielfelten/Projekte/test/packages/name789...
✓ Optimizing tests (57ms)
```

**Comment by superiorsd10** [comment]
Hello @DFelten 👋, 
I wanted to test if my changes to the fork for this issue are correct or not. How can I test it by replicating the project structure provided by you?

**Comment by DFelten** [comment]
> Hello @DFelten 👋, I wanted to test if my changes to the fork for this issue are correct or not. How can I test it by replicating the project structure provided by you?

Hi @superiorsd10, I'm glad you want to implement the feature. The folder structure is described above. You just need to create several packages and run the tests in the root directory.
