### ISSUE TITLE
refactor: include visibleForTesting annotation on test parameters

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_cli#761]
**Description**

Throughout the codebase there are many instances where a class has optional parameters to allow dependency injection during testing, these should be annotated with _visibleForTesting_.

For [example](https://github.com/VeryGoodOpenSource/very_good_cli/blob/e7665fd14e284b752ef620f41b0db88d20f7cc20/lib/src/commands/create/commands/create_subcommand.dart#L55):
```dart
// lib/src/commands/create/commands/create_subcommand.dart
  CreateSubCommand({
    required Analytics analytics,
    required this.logger,
    required MasonGeneratorFromBundle? generatorFromBundle,
    required MasonGeneratorFromBrick? generatorFromBrick,
  })
```

We should intentionally and explicitly denote these as _visibleForTesting_ as:

```dart
// lib/src/commands/create/commands/create_subcommand.dart
  CreateSubCommand({
    required Analytics analytics,
    required this.logger,
    @visibleForTesting required MasonGeneratorFromBundle? generatorFromBundle,
    @visibleForTesting required MasonGeneratorFromBrick? generatorFromBrick,
  })
```

**Expected Behavior**
- To have all parameters that are used exclusively for testing purposes be annotated with _visibleForTesting_.

**Additional Context**
- [visibleForTesting](https://pub.dev/documentation/meta/latest/meta/visibleForTesting-constant.html)

**Comment by superiorsd10** [comment]
Hello @alestiago and @BeatriceMitchell,
I hope you're doing well. I'd like to contribute to the `very_good_cli` and noticed that there's this open issue. Would it be possible to assign this issue to me? I'd be happy to work on it.

Thank you,

**Comment by superiorsd10** [comment]
Hello @alestiago, 
Actually after running the command `dart test`, some of the tests are failing. So can you please help me out in resolving it?

**Comment by alestiago** [comment]
HI @superiorsd10 , thanks for letting us now! I'm happy to help! Do you mind opening a new issue with the test failure you're getting and information about your system (for example, output of `flutter doctor`)? This is mainly to avoid polluting this issue and to allow us referencing to the other issue if the same problem occurs.

**Comment by superiorsd10** [comment]
Hello @alestiago, 
I've opened an issue regarding this. Please look into it. 

[some tests are failing on running dart test](https://github.com/VeryGoodOpenSource/very_good_cli/issues/819)

Thank you,

**Comment by superiorsd10** [comment]
@alestiago Sure! Thank you for the help :)

**Comment by superiorsd10** [comment]
Thank you @alestiago :) The tests are working perfectly fine now. 

I've opened another issue, so could you please consider assigning it to me? 

[fix: markdown formatting mistake in CONTRIBUTING.md file](https://github.com/VeryGoodOpenSource/very_good_cli/issues/822)

Thank you,
