### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by neiljaywarner** [VeryGoodOpenSource/very_good_cli#769]
**Description**

**Steps To Reproduce**

1. very_good create flutter app
2. share on github and push
3. Check the github action job

**Expected Behavior**

build step to pass with zero code changes
   info • Sort directive sections alphabetically • lib/app/view/app.dart:2:1 • directives_ordering
Actual behaviour - 
**Screenshots**
<img width="1650" alt="image" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/3019617/a0185074-d4d5-4027-92b2-9c1a8e5ebb9e">

**Comment by thecodexhub** [comment]
It looks like the `very_good create` command finished abruptly. Cause after bootstrapping, it runs `dart fix --apply` for automated fixes. Would you mind trying the command `dart fix --apply` once in your project terminal, and see if the GitHub workflow runs successfully this time?

If this is not helpful, please share which version of very_good_cli you used to generate your app. Thanks!

**Comment by thecodexhub** [comment]
And please add a good meaningful title for the issue.

**Comment by neiljaywarner** [comment]
So sorry about both. I don't know what happened there. If it finishes abruptly more often I can reopen or file another
