### ISSUE TITLE
[proposal] allow creation of custom projects

### ISSUE THREAD

**Issue by iapicca** [VeryGoodOpenSource/very_good_cli#77]
given the issues
- flutter: 
    - https://github.com/flutter/flutter/issues/15279 
    - https://github.com/flutter/flutter/issues/63284
 - stagehand:
    - https://github.com/dart-lang/stagehand/issues/597
    - https://github.com/dart-lang/stagehand/issues/192

it would be awesome to have the possibility of creating custom `3rd party projects`
other than [Very Good Core](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/doc/very_good_core.md)

possibly following this (dated) [google's own design concept](https://docs.google.com/document/d/1eu6Acdjhwrt5LhyyrE9W0AAZhTKy0R5SqM3I7Wd5fcM/edit?usp=sharing)

**Comment by felangel** [comment]
Hi @iapicca 👋 
Thanks for opening an issue!

In the future, we may support additional, more feature-rich templates as part of `very_good_cli`. That being said, `very_good_cli` is built on top of [mason](https://pub.dev/packages/mason) which allows developers to create their own custom templates. I recommend taking a look at `mason` to see if it meets your needs. If you find it is lacking support for a specific use-case or have any questions feel free to [open an issue in mason](https://github.com/felangel/mason/issues/new) 👍 

Let me know if that helps and thanks for bringing this up! 😄

**Comment by iapicca** [comment]
@felangel 
oh, I didn't know about mason, I'll take a look
but it might be exactly what I was looking for.

closing the issue for now
thank you

**Comment by neiljaywarner** [comment]
@iapicca  did you figure this out? i looked at it and nothing clicked..

**Comment by felangel** [comment]
> @iapicca did you figure this out? i looked at mason and it didn't really make sense to me so far

I'm happy to answer any specific questions and if you haven't already I highly recommend watching out [mason livestream](https://www.youtube.com/watch?v=G4PTjA6tpTU) where we go over how to use mason to create a custom package. Hope that helps 👍
