### ISSUE TITLE
fix: Allow to use .JSON file instead of .ARB for localizations

### ISSUE THREAD

**Issue by ketulrastogi** [VeryGoodOpenSource/very_good_cli#780]
**Description**
We have an already working flutter app that uses JSON data for localization. Can Very Good CLI have similar functionality to localize strings using the JSON data, not the ARB file?

**Comment by renancaraujo** [comment]
Hello there 

What is the advantage of that? AFAIK .arb is based on JSON already.

**Comment by renancaraujo** [comment]
Since this has been silent for some time, I am closing this for now. If you have anything to add, feel free to restart the discussion.
