### ISSUE TITLE
question: workflow coverage_excludes glob 

### ISSUE THREAD

**Issue by neiljaywarner** [VeryGoodOpenSource/very_good_cli#793]
Exclusions don't seem to work as expected
      coverage_excludes: "*.g.dart *.freezed.dart lib/l10n/*" # defaults to "" (none)

gave Lines not covered:
  - lib/discover/discover_repository.g.dart: 42, 51
  - lib/discover/random_user_response.g.dart: 9, 11, 12, 13, 14, 15, 18, 20, 21, 22, 25, 26, 27, 28, 29, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 70, 71, 74, 75, 76, 79, 80, 81, 84, 85, 86, 89, 90, 91, 92, 93, 94, 96, 97, 100, 101, 102, 103, 104, 105, 106, 107, 108, 111, 112, 113, 114, 117, 118, 119, 120, 123, 124, 125, 128, 129, 130, 133, 134, 135, 138, 139, 140, 141, 144, 145, 146, 147, 148, 149, 150, 151, 154, 155, 156, 157, 158, 159, 160, 161, 164, 165, 166, 167, 170, 171, 172, 173, 176, 177, 178, 179, 182, 183, 184, 185, 186

**Comment by renancaraujo** [comment]
Hello there, is this a Very Good CLI issue? I suspect you are talking about a parameter on [Very Good Workflows](https://github.com/VeryGoodOpenSource/very_good_workflows).

Anyway, the glob is not right. Change the first one to `**/*.g.dart` nd it should pass

**Comment by neiljaywarner** [comment]
Thanks so much!  I had a feeling it wasnt vg I just didn't see it... tried
googling and looking for example. I see the spell check include glob now



Sorry about that
....sent from my phone
