### ISSUE TITLE
Exception is thrown when the analytics option was opted out

### ISSUE THREAD

**Issue by NaagAlgates** [VeryGoodOpenSource/very_good_cli#80]
**Description**
An exception is thrown when I opted for no analytics

**Steps To Reproduce**

1. Go to Terminal
2. Enter very_good --analytics
4. Getting the below exception

```
Missing argument for "analytics".
#0      CommandRunner.usageException (package:args/command_runner.dart:95:7)
#1      CommandRunner.parse (package:args/command_runner.dart:123:35)
#2      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:63:27)
#3      main (file:///Users/xxxxxxxxxx/.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.1.1/bin/very_good.dart:5:54)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Expected Behavior**
In my opinion, instead of an exception message, a plain text saying "You have not opted for analytics. To enable it do xxx things"

**Screenshots**
<img width="826" alt="Exception_on_no_analytics" src="https://user-images.githubusercontent.com/14884575/108766603-79e67000-75a9-11eb-8af7-4e50df35cdc5.png">

**Additional Context**
I have just shared my opinion. If this is the expected message, please close this ticket.

**Comment by felangel** [comment]
Hi @NaagAlgates 👋 
Thanks for opening an issue!

The `--analytics` option requires you provide the desired setting:

```sh
# enable analytics
$ very_good --analytics true

# disable analytics
$ very_good --analytics false
```

We'll make sure to improve this in the next release. Thanks for reporting it!🙏

**Comment by NaagAlgates** [comment]
Thank you @felangel , 

I missed the argument "true" or "false"

```
# disable analytics
$ very_good --analytics false
```

It is working now. :)
