### ISSUE TITLE
Unable to execute the newly created project using vgv_cli.

### ISSUE THREAD

**Issue by NaagAlgates** [VeryGoodOpenSource/very_good_cli#82]
**Description**
I was able to successfully create a project using vgv cli. After opening the created project in Vs Code, I get 216 errors.

**Steps To Reproduce**

1. Create a project using cli
2. open it in vs code

**Expected Behavior**
The expected behaviour is to get an executable project without any errors and in an executable condition.

**Screenshots**
<img width="346" alt="Error1" src="https://user-images.githubusercontent.com/14884575/108771024-237c3000-75af-11eb-8736-4dca00594355.png">
<img width="580" alt="Error2" src="https://user-images.githubusercontent.com/14884575/108771025-2545f380-75af-11eb-82ba-6cad8eedc7e7.png">
<img width="314" alt="Error3" src="https://user-images.githubusercontent.com/14884575/108771027-25de8a00-75af-11eb-8c6b-83e113f55d64.png">
<img width="1074" alt="Error4" src="https://user-images.githubusercontent.com/14884575/108771246-7f46b900-75af-11eb-8cd8-35f2ceab0f0c.png">

**Additional Context**
When I tried to run the pug upgrade command, I get the following message

```
[my_first_project_using_vgv_cli] flutter pub upgrade
Running "flutter pub upgrade" in my_first_project_using_vgv_cli...     
The current Dart SDK version is 2.10.5.



Because my_first_project_using_vgv_cli requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub upgrade failed (1; Because my_first_project_using_vgv_cli requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
exit code 1
```

My Flutter Doctor is:
```
Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

Please let me know what I'm missing here.

**Comment by felangel** [comment]
Hi @NaagAlgates 👋 
Thanks for opening an issue!

Because the generated project uses null safety, you need to make sure you're using the beta channel:

```sh
$ flutter channel beta
$ flutter upgrade
```

Hope that helps 👍

**Comment by felangel** [comment]
@NaagAlgates updated the documentation to specify that the generated code requires the beta channel of Flutter due to null safety. If after switching channels you're still having trouble let us know and we're happy to help 👍
