### ISSUE TITLE
refactor: all Mocks should be private

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_cli#827]
**Description**

Throughout the codebase there are instances of public Mocks being used in tests.

Private Mocks benefit from:
- Explicitly tell the reader this is only intended to use in `foo_test.dart`
- Make the test file self contained
- Avoid accidentally importing it in other test files
- Benefit from analyzer warnings once Mocks are no longer used in the file

**Additional Context**
- [Comment suggesting to open this issue](https://github.com/VeryGoodOpenSource/very_good_cli/pull/814#discussion_r1341353530)
- [Comment suggesting change with Hixie](https://github.com/flutter/flutter/pull/107874#discussion_r925445770)

**Comment by droidbg** [comment]
@alestiago I like to pick this up
