### ISSUE TITLE
very_good command fail to run

### ISSUE THREAD

**Issue by mivoligo** [VeryGoodOpenSource/very_good_cli#86]
I'm on Ubuntu 20.04.

When I run `very_good` from terminal I get: 
`/home/michal/.pub-cache/bin/very_good: 8: dart: not found`

But if I run:
`dart "/home/michal/.pub-cache/global_packages/very_good_cli/bin/very_good.dart-2.13.0-30.0.dev.snapshot"`
I get proper output about using _A Very Good Command Line Interface_

Not sure what I'm doing wrong.

**Comment by jorgecoca** [comment]
Hi @mivoligo 👋 

Would you mind running `dart --version` and `flutter doctor` on your terminal and share with me the output? It should look something like this:

```bash
➜  ~ dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

I believe there's something going on with how Dart is installed in your system; comparing outputs should point us in the right direction.

Thanks!

**Comment by mivoligo** [comment]
Thanks for quick reply @jorgecoca 
This is my output:
```
michal@michal-laptop:~$ dart --version
Dart SDK version: 2.13.0-30.0.dev (dev) (Fri Feb 12 04:33:47 2021 -0800) on "linux_x64"
michal@michal-laptop:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.27.0-5.0.pre.73, on Linux, locale pl_PL.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
michal@michal-laptop:~$ 
```

**Comment by jorgecoca** [comment]
Mmmm 🤔  would you mind switching to the `beta` channel and give it a try? 

https://github.com/VeryGoodOpenSource/very_good_cli#-very_good-create

**Comment by mivoligo** [comment]
Sadly, same issue: dart not found.

Output from dart --version and flutter doctor:
```
michal@michal-laptop:~$ dart --version
Dart SDK version: 2.12.0-259.12.beta (beta) (Fri Feb 12 11:00:34 2021 +0100) on "linux_x64"
michal@michal-laptop:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Linux, locale pl_PL.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by felangel** [comment]
@mivoligo can you try deactivating and reactivating the package and sharing the output?

```sh
$ dart pub global deactivate very_good_cli
$ dart pub global activate very_good_cli
```

**Comment by mivoligo** [comment]
Here you go:
```
michal@michal-laptop:~$ dart pub global deactivate very_good_cli
Deactivated package very_good_cli 0.1.2.
michal@michal-laptop:~$ dart pub global activate very_good_cli
Resolving dependencies... (1.3s)
+ args 1.6.0 (2.0.0 available)
+ charcode 1.2.0
+ checked_yaml 1.0.4
+ collection 1.15.0
+ http 0.12.2 (0.13.0 available)
+ http_parser 3.1.4 (4.0.0 available)
+ io 0.3.4
+ json_annotation 3.1.1 (4.0.0 available)
+ mason 0.0.1-dev.26
+ meta 1.3.0
+ mustache_template 1.0.0+1
+ path 1.8.0
+ pedantic 1.10.0
+ recase 3.0.1
+ source_span 1.8.1
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 3.4.2 (4.0.0 available)
+ very_good_analysis 1.0.4
+ very_good_cli 0.1.2
+ yaml 2.2.1 (3.0.0 available)
Precompiling executables... (2.6s)
Precompiled very_good_cli:very_good.
Installed executable very_good.
Activated very_good_cli 0.1.2.
michal@michal-laptop:~$ very_good 
/home/michal/.pub-cache/bin/very_good: 8: dart: not found

```
I'm starting to think the problem could be related to the way I have Flutter SDK installed. I'll try to check some things and let you know.

**Comment by mivoligo** [comment]
So I "fixed" this temporarily by changing `#!/usr/bin/env sh` to  `#!/usr/bin/bash` in `very_good` file.

**Comment by felangel** [comment]
@mivoligo are you having the same issue with other global pub packages? For example, can you activate a package like `stagehand`?

```sh
dart pub global activate stagehand
stagehand --help
```

If this is also failing for you I would recommend [opening an issue on pub](https://github.com/dart-lang/pub/issues) since the file you're editing is generated by `pub`.

**Comment by mivoligo** [comment]
@felangel it's the same issue. 
I've got Flutter SDK installed locally and set `PATH` in `.profile` file. For some reason `sh` doesn't recognize it but `bash` does. So the issue is on my side. I'll close this bag.

**Comment by mivoligo** [comment]
I found my issue. Turns out `dash` (`sh`) doesn't recognise `~` in `PATH`. I had to change it to `$HOME` and after logging off and on again, everything works fine.
