### ISSUE TITLE
flame_game create: No such module 'XCTest'

### ISSUE THREAD

**Issue by jeremiahlukus** [VeryGoodOpenSource/very_good_cli#888]
**Description**

**Steps To Reproduce**
 ```
 very_good create flame_game my_game --desc "My new Flame game"
 flutter pub get
 flutter run --flavor staging --target lib/main_staging.dart
```

Error:
```
Launching lib/main_staging.dart on iPhone 15 Plus in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        648ms
Xcode build done.                                            7.9s
Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'XCTest'
/Users/jeremiah.parrack/freelance/my_game/ios/RunnerTests/RunnerTests.swift:2:7


Could not build the application for the simulator.
Error launching application on iPhone 15 Plus.
```

**Additional Context**
This is on creation of a new flutter_game app using the cli 

```
flutter --version
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (3 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```
Mac OS: 13.6.1

**Comment by gasparhabif** [comment]
Same issue here! I see that the status is In Review but also the fix seems to be merged, any updates?

**Comment by alestiago** [comment]
This is to be released, you can track the progress in this issue https://github.com/VeryGoodOpenSource/very_good_flame_game/issues/135

**Comment by alestiago** [comment]
This has been resolved in Very Good CLI v0.19.0, feel free to re-open if you still encounter the issue in the latest version.

**Comment by alestiago** [comment]
@gasparhabif if you haven't manually modified the iOs directory I recommend deleting it completely and running the command again with the same parameters. You'll be prompted on conflicts, do not overwrite what you don't want to be regenerated.

**Comment by gasparhabif** [comment]
@alestiago Thanks! Although it re created some previously deleted files it worked fine 🚀
