### ISSUE TITLE
feat: Add to the create command --org flag to name the package 

### ISSUE THREAD

**Issue by Yeikel200** [VeryGoodOpenSource/very_good_cli#91]
**Description**
To avoid changing the package name and package identifier after the project is created, example:
`very_good create --org com.yourdomain appname`

**Comment by NaagAlgates** [comment]
Yeah. This is a cool thing to have.

**Comment by deck2020** [comment]
Sorry don't have a clue to what I need. But if Anyone can help I would be willing to pay you. Problem: Estranged Daughter got me to click on links she sent from a parent /children spy app just to see my grandchildren. Not realizing this I did click on link letting spyware start to install. Now access to all accounts. Business personal. Calls are being recorded each time I answer or I call someone. My location camera all in service sending to her. Can you help me? 
I look forward to hearing from you. Thank you in advance.
Deckerdeb39@gmail.com
812 531 6276 text me

**Comment by jorgecoca** [comment]
I might be able to chip in with this soon ;)

**Comment by 0xdanny** [comment]
Hello, if I tried working on this, I presumed that I might need to edit the `very_good_core_bundle.dart` mason bundle used by the 'create' command generator. If so, is this possible(or right) and how can it be done?

**Comment by ikicodedev** [comment]
Any news about this feature?

**Comment by felangel** [comment]
This is now available in [v0.2.4](https://github.com/VeryGoodOpenSource/very_good_cli/releases/tag/v0.2.4) 🎉
