### ISSUE TITLE
fix: FLAVOR_APP_NAME  is not updating for 'Release-Production' in iOS

### ISSUE THREAD

**Issue by hyj1204** [VeryGoodOpenSource/very_good_cli#948]
**Description**
I created a new flutter coro project called 'demo', but in the `FLAVOR_APP_NAME`, it always show`testApp` not the name I set before like `Demo` 
<img width="498" alt="image" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/14248245/fee596b4-86e1-44a3-b6cf-e75000fca223">

**Steps To Reproduce**

1. Create a new flutter core project by CLI
2. Open `Runner.xcodeproj` under iOS folder
3. search `FLAVOR_APP_NAME` under TARGETS Runner

**Expected Behavior**
Show corresponding app name not a fixed text.

**Comment by alestiago** [comment]
Hi @hyj1204  👋 ! Thanks for opening an issue!

I was able to reproduce this issue using Very Good CLI `0.19.1` .
