### ISSUE TITLE
fix: Replacing Icons for Android not reflecting. Suspect .xml file

### ISSUE THREAD

**Issue by tapizquent** [VeryGoodOpenSource/very_good_cli#950]
**Description**
I have adjusted and changed all the icons from the mipmap folders for all three flavors (dev, stg, and prod) but these don't reflect once the app if built.

I have a suspicion that the launch icon is being loaded from an .xml file called `ic_launch_image.xml` instead of the images provided.

Could you please provide a bit more infor around changing the icon properly?

**Comment by tapizquent** [comment]
For reference, yes, that was actually the problem. I removed the `./android/app/src/development/res/mipmap-anydpi-v26/ic_launcher_round.xml` and `./android/app/src/development/res/mipmap-anydpi-v26/ic_launcher.xml`, and just added the `andoird:roundIcon` property to the manifest file.

Changing the images only will not work as most phones seem to build from the xml file instead.

Please would be nice to have some more clear docs around this, given that the icon is set with the VeryGood icons

**Comment by alestiago** [comment]
Hi @tapizquent thanks for opening the issue!

Yes, I agree that we should improve the documentation around the icons. There is an open issue #768. If you would like to write some documentation we can then review your Pull Request. 

For now, I'll be closing this issue as a duplicate if you would like to contribute feel free to drop a comment on #768 asking us to assign you.
