### ISSUE TITLE
Intl : 0.17.0 Failed, because new flutter requires intl to be ^0.18.1

### ISSUE THREAD

**Issue by SayedAkhtar** [VeryGoodOpenSource/very_good_cli#989]
**Description**
Because APP_NAME depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because APP_NAME depends on intl ^0.17.0, version solving failed

**Steps To Reproduce**

1. very_good create flutter_app APP_NAME

**Expected Behavior**
To complete setup of the app without any errors.

**Screenshots**

**Additional Context**
very_good create flutter_app khaabr
⠙ Bootstrapping... (85ms)conflict khaabr/pubspec.lock
Overwrite pubspec.lock? (Yyna) n
⠹ Bootstrapping... (7.1s)conflict khaabr/pubspec.yaml
Overwrite pubspec.yaml? (Yyna) nyes
✓ Generated 240 file(s) (27.0s)
✓ Running "flutter packages get" in ./khaabr (1.4s)
Unhandled exception:
ProcessException: Standard out
Resolving dependencies...
Standard error
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because khaabr depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because khaabr depends on intl ^0.17.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.18.1
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:145:7)
#1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:97:7)
<asynchronous suspension>
#2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:101:11)
<asynchronous suspension>
#3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:304:13)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:87:5)
<asynchronous suspension>
#5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:28:5)
<asynchronous suspension>
#6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:20:5)
<asynchronous suspension>
#7      CreateSubCommand.runCreate (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:226:5)
<asynchronous suspension>
#8      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:200:20)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#11     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#12     main (file:///Users/apple/.pub-cache/hosted/pub.dev/very_good_cli-0.14.0/bin/very_good.dart:5:24)
<asynchronous suspension>

**Comment by alestiago** [comment]
Hi @SayedAkhtar thank you for submitting an issue! Can you provide the output of `flutter doctor`?

**Comment by SayedAkhtar** [comment]
apple@apples-MacBook-Air khaabr % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by alestiago** [comment]
Thank you @SayedAkhtar 💙! I'll try investigating this in the upcoming weeks. You might have to bear with me since I have other tasks with a higher priority 🙌

**Comment by wolfenrain** [comment]
Hey @SayedAkhtar I suspect you were on an older version of the CLI, can you try updating the CLI and testing it again? Sadly the templates in the CLI are not backwards compatible with Flutter when Flutter updates their dependencies

**Comment by tomarra** [comment]
Hi @SayedAkhtar 👋 

Looks like this issue has been solved in the latest version of the CLI. Please update and if you're still having issues you can open a new ticket with updated details.

Closing as "won't fix"
