### ISSUE TITLE
fix: The union plugin I generated has no Android part

### ISSUE THREAD

**Issue by CooolWolf** [VeryGoodOpenSource/very_good_cli#997]
**Description**
The union plugin I generated has no Android part
**Steps To Reproduce**

 See error

**Screenshots**
<img width="1044" alt="image" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/126863650/c4b3b16a-11de-4dc1-a134-93d447fd4925">

I also have a request, when I finish writing an interface, can I generate the interface of the corresponding platform

**Comment by CooolWolf** [comment]
v0.15.0

**Comment by alestiago** [comment]
Hi @CooolWolf thanks for opening an issue 💙 ! Sorry for the late reply 🙌 . Are you still able to reproduce this issue in the latest Very Good CLI version (0.21.0)?

**Comment by alestiago** [comment]
Hey @CooolWolf  since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling.
